/*!
 * Ext JS Library 3.2.0
 * Copyright(c) 2006-2010 Ext JS, Inc.
 * licensing@extjs.com
 * http://www.extjs.com/license
 */
	
countries = [
		{"country":"Afghanistan"},
		{"country":"Albania"},
		{"country":"Algeria"},
		{"country":"Andorra"},
		{"country":"Angola"},
		{"country":"Antigua and Barbuda"},
		{"country":"Argentina"},
		{"country":"Armenia"},
		{"country":"Australia"},
		{"country":"Austria"},
		{"country":"Azerbaijan"},
		{"country":"Bahamas, The"},
		{"country":"Bahrain"},
		{"country":"Bangladesh"},
		{"country":"Barbados"},
		{"country":"Belgium"},
		{"country":"Belize"},
		{"country":"Benin"},
		{"country":"Bermuda"},
		{"country":"Bhutan"},
		{"country":"Bolivia"},
		{"country":"Bosnia and Herzegovina"},
		{"country":"Botswana"},
		{"country":"Brazil"},
		{"country":"Brunei"},
		{"country":"Bulgaria"},
		{"country":"Burkina Faso"},
		{"country":"Burundi"},
		{"country":"Byelarus"},
		{"country":"Cambodia"},
		{"country":"Cameroon"},
		{"country":"Canada"},
		{"country":"Cape Verde"},
		{"country":"Central African Republic"},
		{"country":"Chad"},
		{"country":"Chile"},
		{"country":"China"},
		{"country":"Colombia"},
		{"country":"Comoros"},
		{"country":"Congo"},
		{"country":"Costa Rica"},
		{"country":"Croatia"},
		{"country":"Cuba"},
		{"country":"Cyprus"},
		{"country":"Czech Republic"},
		{"country":"Denmark"},
		{"country":"Djibouti"},
		{"country":"Dominica"},
		{"country":"Dominican Republic"},
		{"country":"Ecuador"},
		{"country":"Egypt"},
		{"country":"El Salvador"},
		{"country":"Equatorial Guinea"},
		{"country":"Eritrea"},
		{"country":"Estonia"},
		{"country":"Ethiopia"},
		{"country":"Falkland Islands (Islas Malvinas)"},
		{"country":"Faroe Islands"},
		{"country":"Fiji"},
		{"country":"Finland"},
		{"country":"France"},
		{"country":"French Guiana"},
		{"country":"French Polynesia"},
		{"country":"Gabon"},
		{"country":"Gambia, The"},
		{"country":"Gaza Strip"},
		{"country":"Georgia"},
		{"country":"Germany"},
		{"country":"Ghana"},
		{"country":"Greece"},
		{"country":"Greenland"},
		{"country":"Grenada"},
		{"country":"Guadeloupe"},
		{"country":"Guatemala"},
		{"country":"Guinea"},
		{"country":"Guinea-Bissau"},
		{"country":"Guyana"},
		{"country":"Haiti"},
		{"country":"Honduras"},
		{"country":"Hong Kong"},
		{"country":"Hungary"},
		{"country":"Iceland"},
		{"country":"India"},
		{"country":"Indonesia"},
		{"country":"Iran"},
		{"country":"Iraq"},
		{"country":"Iraq-Saudi Arabia Neutral Zone"},
		{"country":"Ireland"},
		{"country":"Isle of Man"},
		{"country":"Israel"},
		{"country":"Italy"},
		{"country":"Ivory Coast"},
		{"country":"Jamaica"},
		{"country":"Jan Mayen"},
		{"country":"Japan"},
		{"country":"Jordan"},
		{"country":"Kazakhstan"},
		{"country":"Kenya"},
		{"country":"Kerguelen"},
		{"country":"Kiribati"},
		{"country":"Korea, Peoples Republic of"},
		{"country":"Korea, Republic of"},
		{"country":"Kuwait"},
		{"country":"Kyrgyzstan"},
		{"country":"Laos"},
		{"country":"Latvia"},
		{"country":"Lebanon"},
		{"country":"Lesotho"},
		{"country":"Liberia"},
		{"country":"Libya"},
		{"country":"Liechtenstein"},
		{"country":"Lithuania"},
		{"country":"Luxembourg"},
		{"country":"Macau"},
		{"country":"Macedonia"},
		{"country":"Madagascar"},
		{"country":"Malawi"},
		{"country":"Malaysia"},
		{"country":"Maldives"},
		{"country":"Mali"},
		{"country":"Malta"},
		{"country":"Martinique"},
		{"country":"Mauritania"},
		{"country":"Mauritius"},
		{"country":"Mexico"},
		{"country":"Moldova"},
		{"country":"Monaco"},
		{"country":"Mongolia"},
		{"country":"Morocco"},
		{"country":"Mozambique"},
		{"country":"Myanmar (Burma)"},
		{"country":"Namibia"},
		{"country":"Nepal"},
		{"country":"Netherlands"},
		{"country":"New Caledonia"},
		{"country":"New Zealand"},
		{"country":"Nicaragua"},
		{"country":"Niger"},
		{"country":"Nigeria"},
		{"country":"Northern Mariana Islands"},
		{"country":"Norway"},
		{"country":"Oman"},
		{"country":"Pakistan"},
		{"country":"Panama"},
		{"country":"Papua New Guinea"},
		{"country":"Paraguay"},
		{"country":"Peru"},
		{"country":"Philippines"},
		{"country":"Poland"},
		{"country":"Portugal"},
		{"country":"Puerto Rico"},
		{"country":"Qatar"},
		{"country":"Reunion"},
		{"country":"Romania"},
		{"country":"Russia"},
		{"country":"Rwanda"},
		{"country":"San Marino"},
		{"country":"Sao Tome and Principe"},
		{"country":"Saudi Arabia"},
		{"country":"Senegal"},
		{"country":"Seychelles"},
		{"country":"Sierra Leone"},
		{"country":"Singapore"},
		{"country":"Slovakia"},
		{"country":"Slovenia"},
		{"country":"Solomon Islands"},
		{"country":"Somalia"},
		{"country":"South Africa"},
		{"country":"Spain"},
		{"country":"Sri Lanka"},
		{"country":"St. Christopher-Nevis"},
		{"country":"St. Lucia"},
		{"country":"St. Vincent and the Grenadines"},
		{"country":"Sudan"},
		{"country":"Suriname"},
		{"country":"Svalbard"},
		{"country":"Swaziland"},
		{"country":"Sweden"},
		{"country":"Switzerland"},
		{"country":"Syria"},
		{"country":"Taiwan"},
		{"country":"Tajikistan"},
		{"country":"Tanzania, United Republic of"},
		{"country":"Thailand"},
		{"country":"Togo"},
		{"country":"Tonga"},
		{"country":"Trinidad and Tobago"},
		{"country":"Tunisia"},
		{"country":"Turkey"},
		{"country":"Turkmenistan"},
		{"country":"Turks and Caicos Islands"},
		{"country":"Uganda"},
		{"country":"Ukraine"},
		{"country":"United Arab Emirates"},
		{"country":"United Kingdom"},
		{"country":"United States"},
		{"country":"Uruguay"},
		{"country":"Uzbekistan"},
		{"country":"Vanuatu"},
		{"country":"Venezuela"},
		{"country":"Vietnam"},
		{"country":"Western Sahara"},
		{"country":"Western Samoa"},
		{"country":"Yemen"},
		{"country":"Yugoslavia"},
		{"country":"Zaire"},
		{"country":"Zambia"},
		{"country":"Zimbabwe"}
    ];
	
	