{include file='head.tpl' jsIncludes=[] pageTitle="Citations - CCAFS Climate" pageDescription="Peer-reviewed literature that have cited the CCAFS downscaled climate datasets." keywords="CCAFS,literature,citations,climate change,impacts"}
{include file='header.tpl' current="citations"}
<div id="subheader-image">
  <img src="{$smarty.const.SMARTY_IMG_URI}/ribbon_header_citations.gif" />
</div>
<div id="content" class="citations">
  <h3>Citations of our data</h3>
  <hr>
  <br>
  <h4>The following publications have cited our data:</h4>

  <h5>Peer-reviewed articles</h5>

  <h5>2014</h5>
  <ol>    
    <li>Chapman, D. S., T. Haynes, et al. 2014. <a target="_blank" href="http://www.ncbi.nlm.nih.gov/pubmed/24038855">"Phenology predicts the native and invasive range limits of common ragweed."</a> Global Change Biology 20(1): 192-202.</li>    
    <li>Feng, S., Q. Hu, et al. 2014. <a target="_blank" href="http://www.sciencedirect.com/science/article/pii/S0921818113002403">"Projected climate regime shift under future global warming from multi-model, multi-scenario CMIP5 simulations."</a> Global and Planetary Change 112: 41-52.</li>
    <li>Fraga, H., A. C. Malheiro, et al. 2014. <a target="_blank" href="http://dx.doi.org/10.1007/s10113-013-0490-y">"Very high resolution bioclimatic zoning of Portuguese wine regions: present and future scenarios."</a> Regional Environmental Change 14(1): 295-306.</li>
  </ol>  	

  <h5>2013</h5>
  <ol>
    <li>Byers, J.E., W.G. McDowell, S. Robertson, R. Haynie, L.M. Pintor, and S.B. Wilde. 2013.  <a target="_blank" href="http://dx.doi.org/10.1371/journal.pone.0056812">"Climate and pH predict the spread of the invasive Apple snail (Pomacea insularum) in the southeastern United States."</a> PLoS ONE 8 (2) (February 22): e56812. </li>
    <li>B. Leroy, M. Paschetta, A. Canard, M. Bakkenes, M. Isaia, and F. Ysnel. (2013). <a target="_blank" href="http://www.sciencedirect.com/science/article/pii/S000632071300089X. ">"First assessment of effects of global change on threatened spiders: Potential impacts on Dolomedes plantarius (Clerck) and its conservation plans"</a> Biol. Conserv. 2013;161:155–163.</li>
    <li>Bellard, C., W. Thuiller, et al. 2013. <a target="_blank" href="http://dx.doi.org/10.1111/gcb.12344">"Will climate change promote future invasions? Global Change Biology 19(12): 3740-3748."</a> </li>
    <li>Bucklin, D., J. Watling, et al. 2013. <a target="_blank" href="http://dx.doi.org/10.1007/s10113-012-0389-z">"Climate downscaling effects on predictive ecological models: a case study for threatened and endangered vertebrates in the southeastern United States."</a> Regional Environmental Change 13(1): 57-68.</li>
    <li>Cairns, J., J. Hellin, et al. (2013) <a target="_blank" href="http://rd.springer.com/article/10.1007/s12571-013-0256-x#">"Adapting maize production to climate change in sub-Saharan Africa." </a> Food Security: 1-16. </li>
    <li>Chapman D.S., Haynes T., Beal S., Essl F. & Bullock J.M. (In press). 2013. <a target="_blank" href="http://dx.doi.org/10.1111/gcb.12380">"Phenology Predicts the Native and Invasive Range Limits of Common Ragweed."</a> Global Change Biology: n/a–n/a. doi:10.1111/gcb.12380.</li>
    <li>D’Amen, M., et al. (2013). <a target="_blank" href="http://onlinelibrary.wiley.com/doi/10.1111/j.1466-8238.2012.00774.x/abstract">"Conservation of phylogeographic lineages under climate change."</a> Global Ecology and Biogeography 22(1): 93-104.</li>
    <li>Fandohan B, Gouwakinnou GN, Fonton NH, Sinsin B, Liu J. 2013.  <a target="_blank" href="http://www.pressesagro.be/base/text/v17n3/450.pdf">"Impact Des Changements Climatiques Sur La Répartition Géographique Des Aires Favorables à La Culture et à La Conservation Des Fruitiers Sous-Utilisés : Cas Du Tamarinier Au Bénin"</a> Biotechnology Agronomy Society and Environment 17(3) : 450–462.</li>
    <li>Feng, S. and Q. Fu 2013. <a target="_blank" href="http://www.atmos-chem-phys-discuss.net/13/14637/2013/">"Expansion of global drylands under a warming climate."</a> Atmos. Chem. Phys. Discuss. 13(6): 14637-14665.</li>
    <li>Flavio Lupia, P. N. 2013. <a target="_blank" href="http://www.researchgate.net/publication/245335015_Creazione_di_Geodatabase_per_la_Raccolta_di_Dati_Prodotti_da_Modelli_di_Simulazione_di_Cambiamento_Climatico">"Creazione di Geodatabase per la Raccolta di Dati Prodotti da Modelli di Simulazione di Cambiamento Climatico."</a> </li>
    <li>Gallardo, B. and D.C. Aldridge. 2013.  <a target="_blank" href="http://www.sciencedirect.com/science/article/pii/S0006320713000402">"Evaluating the Combined Threat of Climate Change and Biological Invasions on Endangered Species."</a> Biological Conservation 160 (0) (April): 225–233.</li>
    <li>Giannini T.C., Chapman D.S., Saraiva A.M., Alves-dos-Santos I. & Biesmeijer J.C. 2013.  <a target="_blank" href="http://dx.doi.org/10.1111/j.1600-0587.2012.07191.x ">"Improving Species Distribution Models Using Biotic Interactions: a Case Study of Parasites, Pollinators and Plants."</a> Ecography 36 (6): 649–656. doi:10.1111/j.1600-0587.2012.07191.x. </li>
    <li>Huang, J. G., Y. Bergeron, et al. 2013. <a target="_blank" href="http://www.plosone.org/article/info%3Adoi%2F10.1371%2Fjournal.pone.0056758">"Impact of future climate on radial growth of four major boreal tree species in the Eastern Canadian boreal forest."</a> PloS one 8(2): 28.</li>
    <li>Iwamura, T., A. Guisan, et al. 2013. <a target="_blank" href="http://www.sciencedirect.com/science/article/pii/S0959378013001222">"How robust are global conservation priorities to climate change?"</a> Global Environmental Change 23(5): 1277-1284.</li>
    <li>Kolanowska, M. 2013. <a target="_blank" href="http://europepmc.org/abstract/MED/24143222">"Niche conservatism and the future potential range of Epipactis helleborine (Orchidaceae)."</a> PloS one 8(10): e77352.</li>
    <li>Kroschel, J., M. Sporleder, et al. 2013. <a target="_blank" href="http://dx.doi.org/10.1016/j.agrformet.2012.06.017">"Predicting climate-change-caused changes in global temperature on potato tuber moth Phthorimaea operculella (Zeller) distribution and abundance using phenology modeling and GIS mapping."</a> Agricultural and Forest Meteorology 170(0): 228-241.</li>
    <li>Läderach, P., A. Martinez-Valle, et al. 2013. <a target="_blank" href="http://dx.doi.org/10.1007/s10584-013-0774-8">"Predicting the future climatic suitability for cocoa farming of the world’s leading producer countries, Ghana and Côte d’Ivoire."</a> Climatic Change 119(3-4): 841-854.</li>
    <li>Leroy, B., M. Paschetta, et al. (2013)  <a target="_blank" href="http://www.sciencedirect.com/science/article/pii/S000632071300089X">"First assessment of effects of global change on threatened spiders: Potential impacts on Dolomedes plantarius (Clerck) and its conservation plans." </a> Biological Conservation 161(0): 155-163.</li>
    <li>Machovina, Brian, and Kenneth J Feeley. 2013.  <a target="_blank" href="http://www.sciencedirect.com/science/article/pii/S0921800913002619 ">"Climate Change Driven Shifts in the Extent and Location of Areas Suitable for Export Banana Production."</a> Ecological Economics 95 (0) (November): 83–95.</li>
    <li>Naujokaitis-Lewis, I., J.M.R. Curtis, L. Tischendorf, D. Badzinski, K. Lindsay, M.-J. Fortin. 2013.  <a target="_blank" href="http://dx.doi.org/10.1111/ddi.12063 ">"Uncertainties in Coupled Species Distribution–metapopulation Dynamics Models for Risk Assessments Under Climate Change."</a> Diversity and Distributions 19 (5-6): 541–554. doi:10.1111/ddi.12063. </li>
    <li>Platts PJ, Gereau RE, Burgess ND, Marchant R. 2013.  <a target="_blank" href="http://dx.doi.org/10.1111/j.1600-0587.2012.07805.x">"Spatial Heterogeneity of Climate Change in an Afromontane Centre of Endemism."</a> Ecography 36 (4): 518–530. </li>
    <li>Prisco, I., M. Carboni, et al. 2013. <a target="_blank" href="http://www.plosone.org/article/info%3Adoi%2F10.1371%2Fjournal.pone.0068850">"The fate of threatened coastal dune habitats in Italy under climate change scenarios."</a> PloS one 8(7).</li>
    <li>Prost, S., R. P. Guralnick, et al. 2013. <a target="_blank" href="http://www.ncbi.nlm.nih.gov/pubmed/23505210">"Losing ground: past history and future fate of Arctic small mammals in a changing climate."</a> Global Change Biology 19(6): 1854-1864.</li>
    <li>Rahn, E., P. Läderach, et al. 2013. <a target="_blank" href="http://dx.doi.org/10.1007/s11027-013-9467-x">"Climate change adaptation, mitigation and livelihood benefits in coffee production: where are the synergies?"</a> Mitigation and Adaptation Strategies for Global Change: 1-19.</li>
    <li>Ramirez-Villegas, J., A. J. Challinor, et al. 2013. <a target="_blank" href="http://stacks.iop.org/1748-9326/8/i=2/a=024018">"Implications of regional improvement in global climate models for agricultural impact research."</a> Environmental Research Letters 8(2): 024018.</li>
    <li>Razgour O, Juste J, Ibáñez C, Kiefer A, Rebelo H, Puechmaille SJ, Arlettaz R, Burke T, Dawson DA, Beaumont M, Jones G. 2013.  <a target="_blank" href="http://dx.doi.org/10.1111/ele.12158">"The Shaping of Genetic Variation in Edge-of-Range Populations Under Past and Future Climate Change."</a> Ecology Letters 16 (10): 1258–1266.</li>
    <li>Remesan, R., T. Bellerby, et al. 2013. <a target="_blank" href="http://doi.wiley.com/10.1002/hyp.9872">"Hydrological modelling using data from monthly GCMs in a regional catchment."</a> Hydrological Processes: n/a-n/a.</li>
    <li>Robinet C, Rousselet J, Roques A. 2013.  <a target="_blank" href="http://dx.doi.org/10.1007/s13595-013-0287-7">"Potential Spread of the Pine Processionary Moth in France: Preliminary Results from a Simulation Model and Future Challenges."</a> Annals of Forest Science: 1–12.</li>
    <li>Rodríguez-Pérez, J. R. and J. E. Beltrán-Vargas 2013. <a target="_blank" href="http://revistas.udistrital.edu.co/ojs/index.php/revcie/article/view/5073">"Análisis de escenarios de cambio climático A1B, A2 y B1 para la reserva forestal protectora bosque oriental de Bogotá años 2040, 2070 y 2095 utilizando MarksimGCM."</a> Revista Científica: 167-185.</li>
    <li>Sánchez-Fernández, D., P. Abellán, et al. 2013. <a target="_blank" href="http://dx.doi.org/10.1111/ddi.12104">"Do protected areas represent species' optimal climatic conditions? A test using Iberian water beetles."</a> Diversity and Distributions 19(11): 1407-1417.</li>
    <li>Sangmanee, C. G. W. and S. Pramot 2013. <a target="_blank" href="http://www.mijst.mju.ac.th/vol7/special1.html">"Simulating changes in discharge and suspended sediment loads of the Bangpakong River, Thailand, driven by future climate change."</a> Maejo Int. J. Sci. Technol.(7): 72-84.</li>
    <li>Singh, Piara, S Nedumaran, B R Ntare, K J Boote, N P Singh, K Srinivas, and M C S Bantilan. 2013.  <a target="_blank" href="http://dx.doi.org/10.1007/s11027-012-9446-7">"Potential Benefits of Drought and Heat Tolerance in Groundnut for Adaptation to Climate Change in India and West Africa."</a> Mitigation and Adaptation Strategies for Global Change: 1–21. doi:10.1007/s11027-012-9446-7. </li>
    <li>Skøien, J. O., M. Schulz, et al. 2013. <a target="_blank" href="http://www.sciencedirect.com/science/article/pii/S1574954112001203">"A Model Web approach to modelling climate change in biomes of Important Bird Areas."</a> Ecological Informatics 14(0): 38-43.</li>
    <li>Tuanmu, M.-N., A. Vina, et al. 2013. <a target="_blank" href="http://www.nature.com/nclimate/journal/v3/n3/abs/nclimate1727.html#supplementary-information">"Climate-change impacts on understorey bamboo species and giant pandas in China/'s Qinling Mountains."</a> Nature Clim. Change 3(3): 249-253.</li>
    <li>Van Soesbergen, A. J. J. and M. Mulligan 2013. <a target="_blank" href="http://www.earth-syst-dynam-discuss.net/4/567/2013/">"Modelling multiple threats to water security in the Peruvian Amazon using the WaterWorld Policy Support System."</a> Earth Syst. Dynam. Discuss. 4(1): 567-594.</li>
    <li>Watson, J. E. M., T. Iwamura, et al. 2013. <a target="_blank" href="http://dx.doi.org/10.1038/nclimate2007">"Mapping vulnerability and conservation adaptation strategies under climate change."</a> Nature Clim. Change 3(11): 989-994.</li>
    <li>Watson, James E M, Takuya Iwamura, and Nathalie Butt. 2013.  <a target="_blank" href="http://dx.doi.org/10.1038/nclimate2007">"Mapping Vulnerability and Conservation Adaptation Strategies Under Climate Change."</a> Nature Clim. Change advance online publication (September 15). </li>
    <li>Winzeler, H. E., P. R. Owens, et al. 2013. <a target="_blank" href="https://dl.sciencesocieties.org/publications/sssaj/abstracts/77/1/213">"A Methodology for Examining Changes in Soil Climate Geography through Time: U.S. Soil Moisture Regimes for the Period 1971–2000."</a> Soil Science Society of America Journal 77(1): 213-213.</li>
    <li>Xu, Zhonglin, Zhaodong Feng, Jianjun Yang, Jianghua Zheng, and Fang Zhang. 2013.  <a target="_blank" href="http://dx.doi.org/10.1371/journal.pone.0070728">" Nowhere to invade: Rumex cripus and Typha latifolia projected to disappear under future climate scenarios."</a> PLoS ONE 8 (7) (July 29): e70728.</li>
    <li>Yu, D., M. Chen, et al. 2013. <a target="_blank" href="http://dx.doi.org/10.1007/s10750-012-1213-y">"Global climate change will severely decrease potential distribution of the East Asian coldwater fish Rhynchocypris oxycephalus (Actinopterygii, Cyprinidae)."</a> Hydrobiologia 700(1): 23-32.</li>
  </ol>      

  <h5>2012</h5>
  <ol>
    <li>Beck, J. (2012). <a target="_blank" href="http://link.springer.com/article/10.1007%2Fs10584-012-0481-x?LI=true">"Predicting climate change effects on agriculture from ecological niche modeling: who profits, who loses?"</a>  Climatic Change, 1-13</li> 
    <li>Butler, C. J., et al. (2012). <a target="_blank" href="http://www.bioone.org/doi/abs/10.3159/TORREY-D-11-00049.1">"Distribution of the threatened lace hedgehog cactus (Echinocereus reichenbachii) under various climate change scenarios."</a> The Journal of the Torrey Botanical Society 139(1): 46-55.</li>
    <li>Bütof, A. et al., 2012. <a target="_blank" href="http://onlinelibrary.wiley.com/doi/10.1111/j.1365-2486.2011.02539.x/full">The responses of grassland plants to experimentally simulated climate change depend on land use and region</a>. Global Change Biology, 18(1): 127-137.</li>
    <li>Chung, U., et al. (2011). <a target="_blank" href="http://www.plosone.org/article/info%3Adoi%2F10.1371%2Fjournal.pone.0027439">"Predicting the Timing of Cherry Blossoms in Washington, DC and Mid-Atlantic States in Response to Climate Change."</a> PLoS ONE 6(11): e27439.</li>
    <li>Congli, D., G. Schoups, et al. 2012. <a target="_blank" href="http://web.a.ebscohost.com/abstract?direct=true&profile=ehost&scope=site&authtype=crawler&jrnl=15829596&AN=91924710&h=6uX/deUqR3oXLEWkhdYKYdb3jBEkaxsXkqTjN4b0NuP9PNeJHQTiqyvKppRIYaaoMQIpHnDSkbNSbh8XsA8GEg==&crl=c">"Probabilistic Scenario Development to estimate Future Runoff in the yellow River Basin, China."</a> Environmental Engineering & Management Journal (EEMJ) Vol. 12(Issue 7): p1457-1463. 1457p.</li>
    <li>Cossani, C. M. and M. P. Reynolds 2012. <a target="_blank" href="http://www.plantphysiol.org/content/160/4/1710">"Physiological traits for improving heat tolerance in wheat."</a> Plant Physiol 160(4): 1710-1718.</li>
    <li>Cross, M. S., Schrag, A. M., Girvetz, E. H., & Enquist, C. A. (2012). <a target="_blank" href="http://www.springer.com/environment/global+change+-+climate+change/book/978-1-61091-203-7">"Landscape and Seascape Climate Change Planning and Action."</a> Climate and Conservation, 16-30.</li>
    <li>Daniele de Rigo. (2012). <a target="_blank" href="http://www.iemss.org/sites/iemss2012/proceedings/D3_1_0715_deRigo.pdf.">"Semantic Array Programming for Environmental Modelling: Application of the Mastrave Library"</a> Int. Environ. Model. Softw. Soc. 2012. </li>
    <li>Davis, A. P., et al. (2012). <a target="_blank" href="http://www.plosone.org/article/info%3Adoi%2F10.1371%2Fjournal.pone.0047981">"The Impact of Climate Change on Indigenous Arabica Coffee (Coffea arabica): Predicting Future Trends and Identifying Priorities."</a> PLoS ONE 7(11): e47981.</li>
    <li>Davis, A. P., T. W. Gole, et al. 2012. <a target="_blank" href="http://dx.plos.org/10.1371/journal.pone.0047981">"The impact of climate change on indigenous Arabica coffee (Coffea arabica): predicting future trends and identifying priorities."</a> PloS one 7(11): e47981-e47981.</li>
    <li>Diamond, S. E., L. M. Nichols, et al. 2012. <a target="_blank" href="http://dx.doi.org/10.1890/11-2296.1">"A physiological trait-based approach to predicting the responses of species to experimental climate warming."</a> Ecology 93(11): 2305-2312.</li>
    <li>Diamond, S.E. et al., 2012. <a target="_blank" href="http://people.umass.edu/ideltoro/index_files/ThermalTolerance1.pdf">A global analysis of the climatic, ecological, and evolutionary determinants of warming tolerance in ants</a>. Global Change Biology, 18(2): 448-456.</li>
    <li>Dimitrov, D., D. Nogués-Bravo, et al. 2012. <a target="_blank" href="http://dx.plos.org/10.1371/journal.pone.0048908">"Why do tropical mountains support exceptionally high biodiversity? The Eastern Arc mountains and the drivers of Saintpaulia diversity."</a> PloS one 7(11): e48908-e48908.</li>
    <li>Domisch, S., et al. (2012). <a target="_blank" href="http://onlinelibrary.wiley.com/doi/10.1111/gcb.12107/abstract">"Modelling distribution in European stream macroinvertebrates under future climates."</a> Global Change Biology: n/a-n/a.</li>
    <li>Eitzinger, A., et al. (2012). <a target="_blank" href="http://rd.springer.com/article/10.1007%2Fs11027-012-9432-0?LI=true">"Implications of a changing climate on food security and smallholders’ livelihoods in Bogotá, Colombia."</a> Mitigation and Adaptation Strategies for Global Change: 1-16.</li>
    <li>Eitzinger, A., P. Läderach, et al. 2012. <a target="_blank" href="http://link.springer.com/10.1007/s11027-012-9432-0">"Implications of a changing climate on food security and smallholders’ livelihoods in Bogotá, Colombia."</a> Mitigation and Adaptation Strategies for Global Change 19(2): 161-176.</li>
    <li>Estrada-Peña, A., Sánchez, N., & Estrada-Sánchez, A. (2012). <a target="_blank" href="http://www.ncbi.nlm.nih.gov/pubmed/22448680">"An assessment of the distribution and spread of the tick Hyalomma marginatum in the western Palearctic under different climate scenarios."</a> Vector-Borne and Zoonotic Diseases.</li>
    <li>Feeley, K. J., & Rehm, E. M. (2012). <a target="_blank" href="http://onlinelibrary.wiley.com/doi/10.1111/gcb.12012/abstract">"Amazon's vulnerability to climate change heightened by deforestation and man-made dispersal barriers."</a> Global Change Biology.</li>
    <li>Forrest, J. L., E. Wikramanayake, et al. 2012. <a target="_blank" href="http://www.sciencedirect.com/science/article/pii/S0006320712001437">"Conservation and climate change: Assessing the vulnerability of snow leopard habitat to treeline shift in the Himalaya."</a> Biological Conservation 150(1): 129-135.</li>
    <li>Forrest, J. L., et al. (2012). <a target="_blank" href="http://www.sciencedirect.com/science/article/pii/S0006320712001437">"Conservation and climate change: Assessing the vulnerability of snow leopard habitat to treeline shift in the Himalaya."</a> Biological Conservation 150(1): 129-135.</li>
    <li>Gallagher, R. V., Englert Duursma, D., O’Donnell, J., Wilson, P. D., Downey, P. O., Hughes, L., & Leishman, M. R. (2012). <a target="_blank" href="http://link.springer.com/article/10.1007/s10530-012-0342-6">"The grass may not always be greener: projected reductions in climatic suitability for exotic grasses under future climates in Australia."</a> Biological Invasions, 1-15.</li>
    <li>García-López, J. M., & Allué, C. (2012). <a target="_blank" href="http://www.sciencedirect.com/science/article/pii/S0921818112002299">"Modelling future no-analogue climate distributions: A world-wide phytoclimatic niche-based survey."</a> Global and Planetary Change.</li>
    <li>Giannini, T. C., A. L. Acosta, et al. 2012. <a target="_blank" href="http://dx.doi.org/10.1016/j.ecolmodel.2012.06.035">"Pollination services at risk: Bee habitats will decrease owing to climate change in Brazil."</a> Ecological Modelling 244(0): 127-131.</li>
    <li>Hof AR, Jansson R, Nilsson C. 2012.  <a target="_blank" href="http://dx.doi.org/10.1111/j.1472-4642.2011.00876.x ">"How Biotic Interactions May Alter Future Predictions of Species Distributions: Future Threats to the Persistence of the Arctic Fox in Fennoscandia."</a> Diversity and Distributions 18 (6): 554–562. </li>
    <li>Hof AR, Jansson R, Nilsson C. 2012.  <a target="_blank" href="http://www.pubmedcentral.nih.gov/articlerender.fcgi?artid=3527567&tool=pmcentrez&rendertype=abstract">"Future Climate Change Will Favour Non-Specialist Mammals in the (sub)arctics."</a> PloS One 7 (12) (January): e52574. </li>
    <li>Hof AR, Jansson R, Nilsson C. 2012.  <a target="_blank" href="http://www.sciencedirect.com/science/article/pii/S0304380012003778 ">"The Usefulness of Elevation as a Predictor Variable in Species Distribution Modelling."</a> Ecological Modelling 246 (0) (November 10): 86–90.</li>
    <li>Hof, A. R., R. Jansson, et al. 2012. <a target="_blank" href="http://www.plosone.org/article/info%3Adoi%2F10.1371%2Fjournal.pone.0052574">"Future climate change will favour non specialist mammals in the (Sub)arctics."</a> PLoS ONE 7(12): e52574.</li>
    <li>Hof, A. R., R. Jansson, et al. 2012. <a target="_blank" href="http://onlinelibrary.wiley.com/doi/10.1111/j.1472-4642.2011.00876.x/abstract">"How biotic interactions may alter future predictions of species distributions: future threats to the persistence of the arctic fox in Fennoscandia."</a> Diversity and Distributions, 18: 554-562.</li>
    <li>Hof, A. R., R. Jansson, et al. 2012. <a target="_blank" href="http://www.sciencedirect.com/science/article/pii/S0304380012003778">"The usefulness of elevation as a predictor variable in species distribution modelling."</a> Ecological Modelling: 246: 286-290.</li>
    <li>Huang, P., & Schaal, B. A. (2012). <a target="_blank" href="http://www.ncbi.nlm.nih.gov/pubmed/23125436">"Association between the geographic distribution during the last glacial maximum of Asian wild rice, Oryza rufipogon (Poaceae), and its current genetic variation."</a> American journal of botany, 99(11), 1866-1874.</li>
    <li>Hughes, A. C., et al. (2012). <a target="_blank" href="http://onlinelibrary.wiley.com/doi/10.1111/j.1365-2486.2012.02641.x/abstract">"The projected effects of climatic and vegetation changes on the distribution and diversity of Southeast Asian bats."</a> Global Change Biology 18(6): 1854-1865.</li>
    <li>Ihlow, F. et al., 2012. <a target="_blank" href="http://onlinelibrary.wiley.com/doi/10.1111/j.1365-2486.2011.02623.x/full">On the brink of extinction? How climate change may affect global chelonian species richness and distribution</a>. Global Change Biology. DOI: 10.1111/j.1365-2486.2011.02623.x.</li>
    <li>Jarvis, A., Ramirez-Villegas, J., Herrera Campo, B. and Navarro-Racines, C., 2012. <a target="_blank" href="http://www.springerlink.com/content/n36675226277455j">Is Cassava the Answer to African Climate Change Adaptation?</a> Tropical Plant Biology: 1-21.</li>
    <li>Jones, G. V. and F. Alves 2012. <a target="_blank" href="http://dx.doi.org/10.1504/IJGW.2012.049448">"Impact of climate change on wine production: a global overview and regional assessment in the Douro Valley of Portugal."</a> International Journal of Global Warming 4(3): 383-406.</li>
    <li>Kapeller, S., M. J. Lexer, et al. 2012. <a target="_blank" href="http://www.sciencedirect.com/science/article/pii/S0378112712000631">"Intraspecific variation in climate response of Norway spruce in the eastern Alpine range: Selecting appropriate provenances for future climate."</a> Forest Ecology and Management 271: 46-57.</li>
    <li>Keller, S. R., Levsen, N., Olson, M. S., & Tiffin, P. (2012). <a target="_blank" href="http://www.ncbi.nlm.nih.gov/pubmed/22513286">"Local Adaptation in the Flowering-Time Gene Network of Balsam Poplar, Populus balsamifera L."</a> Molecular Biology and Evolution, 29(10), 3143-3152.</li>
    <li>Lee DN, Papeş M, Van Den Bussche RA. 2012.  <a target="_blank" href="http://dx.doi.org/10.1371/journal.pone.0042466 ">"Present and Potential Future Distribution of Common Vampire Bats in the Americas and the Associated Risk to Cattle."</a> PLoS ONE 7 (8) (August 10): e42466. </li>
    <li>Lee, D. N., M. Papeş, et al. 2012. <a target="_blank" href="http://dx.plos.org/10.1371/journal.pone.0042466">"Present and potential future distribution of common vampire bats in the Americas and the associated risk to cattle."</a> PloS one 7(8): e42466-e42466.</li>
    <li>Loiseau, C., et al. (2012). <a target="_blank" href="http://www.plosone.org/article/info%3Adoi%2F10.1371%2Fjournal.pone.0044729">"First Evidence and Predictions of <italic>Plasmodium</italic> Transmission in Alaskan Bird Populations."</a> PLoS ONE 7(9): e44729.</li>
    <li>Loyola, R. D., Lemes, P., Faleiro, F. V., Trindade-Filho, J., & Machado, R. B. (2012). <a target="_blank" href="http://www.plosone.org/article/info:doi/10.1371/journal.pone.0046257">"Severe loss of suitable climatic conditions for marsupial species in Brazil: challenges and opportunities for conservation."</a> PloS one, 7(9), e46257</li>
    <li>Luedeling, E., & Neufeldt, H. (2012). <a target="_blank" href="http://link.springer.com/article/10.1007%2Fs10584-012-0438-0">"Carbon sequestration potential of parkland agroforestry in the Sahel."</a> Climatic Change, 1-19.</li>
    <li>Luna-Vega, I., et al. (2012). <a target="_blank" href="http://www.nrcresearchpress.com/doi/abs/10.1139/b2012-019#.UM8trXf8J8F">"Ecological niche modeling on the effect of climatic change and conservation of Ternstroemia lineata DC. (Ternstroemiaceae) in Mesoamerica."</a> Botany 90(7): 637-650.</li>
    <li>Luna-Vega, I., O. Alcántara-Ayala, et al. 2012. <a target="_blank" href="http://www.nrcresearchpress.com/doi/abs/10.1139/b2012-019#.UvULWvl5M1I">"Ecological niche modeling on the effect of climatic change and conservation of Ternstroemia lineata DC. (Ternstroemiaceae) in Mesoamerica."</a> Botany 90(7): 637-650.</li>
    <li>Markovic, D., Freyhof, J., & Wolter, C. (2012). <a target="_blank" href="http://www.plosone.org/article/info%3Adoi%2F10.1371%2Fjournal.pone.0040530">"Where Are All the Fish: Potential of Biogeographical Maps to Project Current and Future Distribution Patterns of Freshwater Species."</a> PloS one, 7(7), e40530.</li>
    <li>Mbatudde, M., Mwanjololo, M., Kakudidi, E. K., & Dalitz, H. (2012). <a target="_blank" href="http://onlinelibrary.wiley.com/doi/10.1111/j.1365-2028.2012.01327.x/abstract">"Modelling the potential distribution of endangered Prunus africana (Hook. f.) Kalkm. in East Africa."</a> African Journal of Ecology.</li>
    <li>Nadav Nur, Leonardo Salas, Samuel Veloz, Julian Wood, Leonard Liu, and Grant Ballard . (2012). <a target="_blank" href="http://climate.calcommons.org/sites/default/files/LCC%20PRBO%20SFBay%20TidalMarsh%20Demogr%20ClimateChange_2012.pdf">"Assessing Vulnerability of Tidal Marsh Birds to Climate Change through the Analysis of Population Dynamics and Viability. Technical Report."</a> Report to the California Landscape Conservation Cooperative. Version 1.0</li>
    <li>Nyabako, T. and E. Manzungu (2012). <a target="_blank" href="http://www.ccsenet.org/journal/index.php/enrr/article/view/15244/10593">"An Assessment of the Adaptability to Climate Change of Commercially Available Maize Varieties in Zimbabwe."</a> Environment and Natural Resources Research 2(1).</li>
    <li>Pfenninger, M., Bálint, M., & Pauls, S. U. (2012). <a target="_blank" href="http://www.biomedcentral.com/1471-2148/12/224">"Methodological framework for projecting the potential loss of intraspecific genetic diversity due to global climate change."</a> BMC evolutionary biology, 12(1), 224.</li>
    <li>Platts, P. J., et al. (2012). <a target="_blank" href="http://onlinelibrary.wiley.com/doi/10.1111/j.1600-0587.2012.07805.x/abstract">"Spatial heterogeneity of climate change in an Afromontane centre of endemism."</a> Ecography.</li>
    <li>Rahimi, J., M. Ebrahimpour, et al. 2012. <a target="_blank" href="http://link.springer.com/10.1007/s00704-012-0741-8">"Spatial changes of Extended De Martonne climatic zones affected by climate change in Iran."</a> Theoretical and Applied Climatology 112(3-4): 409-418.</li>
    <li>Ramirez-Villegas, J. and A. Challinor 2012. <a target="_blank" href="http://www.sciencedirect.com/science/article/pii/S0168192312001244">"Assessing relevant climate data for agricultural applications."</a> Agricultural and Forest Meteorology 161: 26-45.</li>
    <li>Rocha, J., A. Crespí, et al. 2012. <a target="_blank" href="http://dx.doi.org/10.1080/17550874.2012.671857">"Status and conservation of Silene section Cordifolia in the Iberian Peninsula: a menaced group under global environmental change."</a> Plant Ecology & Diversity 5(1): 45-56.</li>
    <li>Rodríguez-Castañeda G, Hof AR, Jansson R, Harding LE. 2012.  <a target="_blank" href="http://dx.doi.org/10.1371/journal.pone.0044402">"Predicting the Fate of Biodiversity Using Species’ Distribution Models: Enhancing Model Comparability and Repeatability."</a> PLoS ONE 7 (9) (September 11): e44402. </li>
    <li>Rodríguez-Castañeda, G., A. R. Hof, et al. 2012. <a target="_blank" href="http://europepmc.org/abstract/MED/22984502">"Predicting the fate of biodiversity using species' distribution models: enhancing model comparability and repeatability."</a> PloS one 7(9): e44402.</li>
    <li>Romo, H., Sanabria, P., & García-Barros, E. (2012) <a target="_blank" href="http://www.uam.es/personal_pdi/ciencias/egb/download/Romo_et_al_2012_Prediccion_impactos_Boloria.pdf">"Predicción de los impactos del cambio climático en la distribución de lepidópteros del género Boloria Moore, 1900 en la Península Ibérica (Lepidoptera: Nymphalidae)."</a> </li>
    <li>Shah, R. D. T., D. Narayan Shah, et al. 2012. <a target="_blank" href="http://dx.doi.org/10.1080/13887890.2012.697399">"Range shifts of a relict Himalayan dragonfly in the Hindu Kush Himalayan region under climate change scenarios."</a> International Journal of Odonatology 15(3): 209-222.</li>
    <li>Shah, Ram Devi Tachamo, Deep Narayan Shah, and Sami Domisch. 2012.  <a target="_blank" href="http://dx.doi.org/10.1080/13887890.2012.697399">"Range Shifts of a Relict Himalayan Dragonfly in the Hindu Kush Himalayan Region Under Climate Change Scenarios."</a> International Journal of Odonatology 15 (3) (July 10): 209–222. </li>
    <li>Singh, P., et al. (2012). <a target="_blank" href="http://onlinelibrary.wiley.com/doi/10.1111/j.1439-037X.2012.00522.x/abstract">"Evaluation of Genetic Traits for Improving Productivity and Adaptation of Groundnut to Climate Change in India."</a> Journal of Agronomy and Crop Science 198(5): 399-413.</li>
    <li>Sonder, K., C. C. Okonkwo, et al. 2010. <a target="_blank" href="http://repository.cimmyt.org/xmlui/handle/10883/3324?show=full">"Predicted changes in suitability and agro climatic factors due to climate change for yam production in Nigeria."</a> African Journal of Root and Tuber Crops 8(2): 51-59.</li>
    <li>Song, L., et al. (2012). <a target="_blank" href="http://www.sciencedirect.com/science/article/pii/S000632071200184X">"Response of non-vascular epiphytes to simulated climate change in a montane moist evergreen broad-leaved forest in southwest China."</a> Biological Conservation 152(0): 127-135.</li>
    <li>Song, L., W.-Y. Liu, et al. 2012. <a target="_blank" href="http://dx.doi.org/10.1016/j.biocon.2012.04.002">"Response of non-vascular epiphytes to simulated climate change in a montane moist evergreen broad-leaved forest in southwest China."</a> Biological Conservation 152(0): 127-135.</li>
    <li>Thomas, E., et al. (2012). <a target="_blank" href="http://www.plosone.org/article/info%3Adoi%2F10.1371%2Fjournal.pone.0047676">"Present Spatial Diversity Patterns of Theobroma cacao L. in the Neotropics Reflect Genetic Differentiation in Pleistocene Refugia Followed by Human-Influenced Dispersal."</a> PLoS ONE 7(10): e47676. </li>
    <li>Velásquez-Tibatá, J., P. Salaman, et al. 2012. <a target="_blank" href="http://link.springer.com/10.1007/s10113-012-0329-y">"Effects of climate change on species distribution, community structure, and conservation of birds in protected areas in Colombia."</a> Regional Environmental Change 13(2): 235-248.</li>
    <li>Velásquez-Tibatá, J., Salaman, P., & Graham, C. H. (2012). <a target="_blank" href="http://link.springer.com/article/10.1007%2Fs10113-012-0329-y">" Effects of climate change on species distribution, community structure, and conservation of birds in protected areas in Colombia."</a> Regional Environmental Change, 1-14</li>
    <li>Velásquez-Tibatá, Jorge, Paul Salaman, and Catherine H. Graham. 2012.  <a target="_blank" href="http://link.springer.com/10.1007/s10113-012-0329-y">"Effects of Climate Change on Species Distribution, Community Structure, and Conservation of Birds in Protected Areas in Colombia."</a> Regional Environmental Change 13 (2) (July 7): 235–248. doi:10.1007/s10113-012-0329-y.</li>
  </ol>

  <h5>2011</h5>
  <ol>
    <li>Dempe, H., Bittner, T., Jaeschke, A., & Beierkuhnlein, C. (2011). <a target="_blank" href="environmental envelope modelling to nature conservation strategies.">"Habitat coherence and climate change: an analysis application for the Natura 2000 network in Germany. Climate change impacts on habitats and biodiversity"</a> environmental envelope modelling to nature conservation strategies.</li>
    <li>Heubes, J. et al., 2011. <a target="_blank" href="http://onlinelibrary.wiley.com/doi/10.1111/j.1365-2699.2011.02560.x/full">Modelling biome shifts and tree cover change for 2050 in West Africa</a>. Journal of Biogeography, 38(12): 2248-2258.</li>
    <li>Hof AR. 2011. <a target="_blank" href=" ">" European terrestrial gastropod distribution. How may climate change affect their diversity and current distribution. In: Bianchi, A. and Fields, J. (eds), Gastropods: Diversity, Habitat and Genetics."</a> Nova Science Publishers, Inc., Hauppauge, New York pp. 165-182</li>
    <li>Jarvis, A., Lane, A. and Hijmans, R.J., 2008. <a target="_blank" href="http://www.sciencedirect.com/science/article/pii/S0167880908000133">The effect of climate change on crop wild relatives</a>. Agriculture, Ecosystems &amp; Environment, 126(1-2): 13-23.</li>
    <li>Jenkins, C.N. et al., 2011. <a target="_blank" href="http://onlinelibrary.wiley.com/doi/10.1111/j.1472-4642.2011.00770.x/abstract">Global diversity in light of climate change: the case of ants</a>. Diversity and Distributions, 17(4): 652-662.</li>
    <li>Laderach, P., M. Lundy, et al. 2011. <a target="_blank" href="http://link.springer.com/chapter/10.1007%2F978-3-642-14776-0_42">"Predicted Impact of Climate Change on Coffee Supply Chains. The Economic, Social and Political Elements of Climate Change."</a> W. Leal Filho, Springer Berlin Heidelberg: 703-723.</li>
    <li>Loiselle, B.A., Graham, C.H., Goerck, J.M. and Ribeiro, M.C., 2010. <a target="_blank" href="http://onlinelibrary.wiley.com/doi/10.1111/j.1365-2699.2010.02285.x/full">Assessing the impact of deforestation and climate change on the range size and environmental niche of bird species in the Atlantic forests, Brazil</a>. Journal of Biogeography, 37(7): 1288-1301.</li>
    <li>Mulligan, M. et al., 2010. <a target="_blank" href="http://www.infoandina.org/sites/default/files/recursos/the_andes_basins.pdf">The Andes basins: biophysical and developmental diversity in a climate of change</a>. Water International, 35(5): 472-492.</li>
    <li>Mulligan, M. et al., 2011. <a target="_blank" href="www.tandfonline.com/doi/abs/10.1080/02508060.2011.543408">The nature and impact of climate change in the Challenge Program on Water and Food (CPWF) basins</a>. Water International, 36(1): 96-124.</li>
    <li>Ramirez-Villegas, J., Jarvis, A. and Läderach, P., 2011. <a target="_blank" href="http://www.sciencedirect.com/science/article/pii/S0168192311002814">Empirical approaches for assessing impacts of climate change on agriculture: The EcoCrop model and a case study with grain sorghum</a>. Agricultural and Forest Meteorology: 1-12.</li>
    <li>Rödder, D. and Schulte, U., 2010. <a target="_blank" href="http://www.springerlink.com/content/7575225168472135">Potential loss of genetic variability despite well established network of reserves: the case of the Iberian endemic lizard <i>Lacerta schreiberi</i></a>. Biodiversity and Conservation, 19(9): 2651-2666.</li>
    <li>Rödder, D., Bohme, W., and Lotters, S., 2011. <a target="_blank" href="http://www.salamandra-journal.com/index.php?option=com_docman&amp;task=doc_download&amp;gid=233&amp;Itemid=72">'Chamaliens' on the Hawaiian Islands: spatial risk assessment for the invasive Jackson's chameleon (Chamaeleonidae)</a>. Salamandra 47(1): 36-42. ISSN 0036-3375.</li>
    <li>Schroth, G. et al., 2009. <a target="_blank" href="http://www.springerlink.com/content/q664004556lt471w">Towards a climate change adaptation strategy for coffee communities and ecosystems in the Sierra Madre de Chiapas, Mexico</a>. Mitigation and Adaptation Strategies for Global Change, 14(7): 605-625.</li>
    <li>Stensgaard, A.S. et al., 2011. <a target="_blank" href="http://www.sciencedirect.com/science/article/pii/S0001706X11003366">Large-scale determinants of intestinal schistosomiasis and intermediate host snail distribution across Africa: Does climate matter?</a> Acta Tropica.</li>
  </ol>

  <h5>&lt; 2010</h5>
  <ol>
    <li> Giraldo, D., Juarez, H., Pérez, W., Trebejo, I., Yzarra, W. & Forbes G. (2010) <a target="_blank" href="Severidad del tizón tardío de la papa (Phytophthora infestans) en zonas agrícolas del Perú asociado con el cambio climático.">"Severidad del tizón tardío de la papa (Phytophthora infestans) en zonas agrícolas del Perú asociado con el cambio climático."</a> Revista Peruana Geo-Atmosférica Rpga (2), 56-67. </li>
    <li> Jarvis, A., Lane, A. and Hijmans, R.J., 2008. <a target="_blank" href="http://www.sciencedirect.com/science/article/pii/S0167880908000133">"The effect of climate change on crop wild relatives."</a> Agriculture, Ecosystems & Environment, 126(1-2): 13-23.</li>
    <li> Loiselle, B.A., Graham, C.H., Goerck, J.M. and Ribeiro, M.C., 2010. <a target="_blank" href="http://onlinelibrary.wiley.com/doi/10.1111/j.1365-2699.2010.02285.x/full">"Assessing the impact of deforestation and climate change on the range size and environmental niche of bird species in the Atlantic forests, Brazil."</a> Journal of Biogeography, 37(7): 1288-1301.</li>
    <li> Mulligan, M. et al., 2010. <a target="_blank" href="http://www.infoandina.org/sites/default/files/recursos/the_andes_basins.pdf">"The Andes basins: biophysical and developmental diversity in a climate of change."</a> Water International, 35(5): 472-492.</li>
    <li> Rödder, D. and Schulte, U., 2010.  <a target="_blank" href="http://www.springerlink.com/content/7575225168472135">"Potential loss of genetic variability despite well established network of reserves: the case of the Iberian endemic lizard Lacerta schreiberi."</a> Biodiversity and Conservation, 19(9): 2651-2666.</li>
    <li> Schroth, G. et al., 2009. <a target="_blank" href="http://www.springerlink.com/content/q664004556lt471w">"Towards a climate change adaptation strategy for coffee communities and ecosystems in the Sierra Madre de Chiapas, Mexico."</a> Mitigation and Adaptation Strategies for Global Change, 14(7): 605-625.</li>
  </ol>

  <h5>Book chapters</h5>
  <ol>
    <li>Beebe, S. et al., 2011. <a target="_blank" href="http://onlinelibrary.wiley.com/doi/10.1002/9780470960929.ch25/summary">Chapter 16: Genetic Improvement of Common Beans and the Challenges of Climate Change</a>. Crop Adaptation to Climate Change. Wiley &amp; Sons.</li>
    <li>Carne, C., Semple, S., Lehmann, J. 2012.  Chapter 14: <a target="_blank" href="http://ntrs.nasa.gov/archive/nasa/casi.ntrs.nasa.gov/20120013440_2012013015.pdf#page=327">"The Effects of Climate Change on Orangutans: A Time Budget Model"</a>. Climate Models. InTech.</li>
    <li>Ceballos, H., Ramirez-Villegas, J., Bellotti, A.C., Jarvis, A. and Alvarez, E., 2011. <a target="_blank" href="http://www.wiley.com/WileyCDA/WileyTitle/productCd-0813820162.html">Chapter 19: Adaptation of Cassava to Changing Climates</a>. Crop Adaptation to Climate Change. Wiley &amp; Sons.</li>
    <li>Druyan, L. M. 2012. <a target="_blank" href="http://pubs.giss.nasa.gov/abs/dr07300k.html">"Climate Models."</a> Croatia. InTech.</li>
    <li>Giannini, T. C., A. L. Acosta, et al. 2012. <a target="_blank" href="http://myrtus.uspnet.usp.br/statuspolin/17.html">"Impacto de mudanças climáticas em abelhas solitárias: um estudo de caso envolvendo duas espécies de Centris. Polinizadores no Brasil."</a> São Paulo, EDUSP: 335 - 348.</li>
    <li>Hof, A. R. 2011. <a target="_blank" href="http://umu.diva-portal.org/smash/record.jsf?pid=diva2:462007">"European terrestrial gastropod distribution. How may climate change affect their diversity and current distribution."</a> Nova Science Publishers, Inc.: 165-182.</li>
    <li>Jarvis, A., J. Ramírez-Villegas, et al. 2013. <a target="_blank" href="http://ciat.cgiar.org/wp-content/uploads/2012/12/chapter_3_eco_efficiency.pdf">"Are Climate Change Adaptation and Mitigation Options Eco-Efficient? Eco-Efficiency: From Vision to Reality. I. C. f. T. A."</a> (CIAT). Cali, Colombia.</li>
    <li>Jarvis, A., Ramirez-Villegas, J., Bonilla-Findji, O. and Zapata, E., 2011. <a target="_blank" href="http://www.wiley.com/WileyCDA/WileyTitle/productCd-0813820162.html">Chapter 3.1: Impacts of Climate Change on Crop Production in Latin America</a>. Crop Adaptation to Climate Change. Wiley &amp; Sons.</li>
    <li>Ramirez-Villegas, J., A. Jarvis, et al. 2013. <a target="_blank" href="http://www.publish.csiro.au/pid/7037.htm">"Crop and forage genetic resources: international interdependence in the face of climate change. Crop genetic resources as a global commons: challenges in international law and governance."</a> p78-98.</li>
    <li>Ramirez-Villegas, J., Jarvis, A., Van den Bergh, I., Staver, C. and Turner, D., 2011. <a target="_blank" href="http://www.wiley.com/WileyCDA/WileyTitle/productCd-0813820162.html">Chapter 20: Changing Climates: Effects on Growing Conditions for Banana and Plantain (<i>Musa</i> spp.) and Possible Responses</a>. Crop Adaptation to Climate Change. Wiley &amp; Sons.</li>
    <li>Ribeiro, M. C., Camargo Martensen, A., Metzger, J.P., Tabarelli, M., Scarano, F., and Fortin, M.J., 2011. <a target="_blank" href="http://www.springer.com/life+sciences/ecology/book/978-3-642-20991-8">Chapter 21: The Brazilian Atlantic Forest: A Shrinking Biodiversity Hostpot</a>. Biodiversity Hotspots. Springer Verlag, ISBN 978-3-642-20991-8.</li>
    <li>Schafleitner, R. et al., 2011. <a target="_blank" href="http://www.wiley.com/WileyCDA/WileyTitle/productCd-0813820162.html">Chapter 11: Adaptation of the Potato Crop to Changing Climates</a>. Crop Adaptation to Climate Change. Wiley &amp; Sons.</li>
  </ol>

  <h5>Theses and reports</h5>
  <ol>
    <li>Anayah, Fathi M A. 2012. <a target="_blank" href="http://digitalcommons.usu.edu/cgi/viewcontent.cgi?article=2263&context=etd">"Improving Complementary Methods To Predict Evapotranspiration For Data Deficit Conditions and Global Applications Under Climate Change."</a> All Graduate Theses and Dissertations.Paper 1306.</li>
    <li>Caley, P., Tennant, P., and Hood, G., 2011. <a target="_blank" href="http://www.feral.org.au/wp-content/uploads/2011/06/ClimateChangeRept.pdf">Modelling the distribution of vertebrate pests in New South Wales under climate change</a>. Invasive Animals Cooperative Research Centre. University of Canberra, ACT 2600, May 2011. ISBN: 978-1-921777-08-0.</li>
    <li>ADB 2009. <a target="_blank" href="http://www.ifad.org/drd/agriculture/132.htm">"Climate Change, Food Security, and Sound Economic Livelihood in Pacific Island Countries."</a>  Mandaluyong City, Philippines, Asian Development Bank.</li>
    <li>Aguilar, R. 2012. <a target="_blank" href="http://www.pieb.com.bo/agua_preeva.php?id=2">"Evaluación de la vulnerabilidad, amenazas y riesgos asociados al cambio climático para la planificación del desarrollo en el municipio de Yunchará."</a> Yunchará, Bolivia, PROMETA.</li>
    <li>Anayah, F. M. A. 2012. <a target="_blank" href="http://digitalcommons.usu.edu/etd/1306/">"Improving Complementary Methods To PredictEvapotranspiration For Data Deficit Conditionsand Global Applications Under Climate Change."</a>  All Graduate Theses and Dissertations. Utah, Utah State University. PhD Civil and Environmental Engineering.</li>
    <li>Caffrey, P. e. a. 2013. <a target="_blank" href="http://community.eldis.org/.5bb2fb84">"Uganda Climate Change Vulnerability Assessment Report."</a>  Uganda: 76-76.</li>
    <li>CIAT 2013. <a target="_blank" href="http://dapa.ciat.cgiar.org/wp-content/uploads/big-files/2013/Resumen_Final_v5_new.pdf">"Evaluación de la vulnerabilidad al cambio climático de la agricultura y del recurso hídrico en los Andes de Colombia, Ecuador y Perú."</a>  Cali, Colombia, Área de Investigación en Análisis de Políticas (DAPA) - Centro Internacional de AgriculturaTropical (CIAT) </li>
    <li>Crego, R. D. 2012. <a target="_blank" href="http://search.proquest.com/docview/1313220759">"Modeling the distribution of meadows in arid and Semi-Arid Patagonia, Argentina: assessing current distribution and predicting response to climate change. Carbondale."</a> Department of Forestry, Southern Illinois University </li>
    <li>Jalloh, Abdulai, Gerald C. Nelson, Timothy S. Thomas, Robert Zougmoré, and Harold Roy-Macauley, eds. 2013.  <a target="_blank" href="">"West African Agriculture and Climate Change: A Comprehensive Analysis."</a>  IFPRI Research Monograph. Washington: International Food Policy Research Institute. Available at IFPRI.org.</li>
    <li>Jones, H. 2013. <a target="_blank" href="http://dukespace.lib.duke.edu/dspace/handle/10161/6819">"Mechanistic Habitat Modeling with Multi-Model Climate Ensembles."</a>  Nicholas School of the Environment and Earth Sciences, Duke University.</li>
    <li>Kate, P.,2012. <a target="_blank" href="">"Using a spatial model of geodiversity to guide conservation within mountains at the pan-tropical-scale"</a> PhD. Thesis. University of Southampton</li>
    <li>Läderach, P. 2011. <a target="_blank" href="http://www.eldis.org/go/home&id=60505&type=Document#.UvzKPLTpF8E">"Predicting the Impact of Climate Change on the Cocoa - Growing Regions in Ghana and Cote d’Ivoire."</a> CGIAR Research Program on Climate Change and Food Security (CCAFS).</li>
    <li>Laderach, P. and A. Eitzinger 2011. <a target="_blank" href="http://www.eldis.org/go/home&id=59073&type=Document#.UvzKU7TpF8E">"Future Climate Scenarios for Uganda’s Tea Growing Areas."</a>  Cali, Colombia - Managua, Nicaragua, International Center for Tropical Agriculture (CIAT).</li>
    <li>Laderach, P. and A. Eitzinger 2012. <a target="_blank" href="http://www.coffeeandclimate.org/reports_studies.html">"Future Climate Scenarios for Tanzania’s Arabica Coffee Growing Areas."</a>  Cali, Colombia, International Center for Tropical Agriculture (CIAT).</li>
    <li>Läderach, P., A. Eitzinger, et al. 2011. <a target="_blank" href="http://dapa.ciat.cgiar.org/wp-content/uploads/2011/07/Methodology-Report.pdf">"Adaptation by agricultural communities to climate change through participatory & supply chain inclusive management."</a>  Managua, Nicaragua and Cali, Colombia, International Center for Tropical Agriculture (CIAT).</li>
    <li>Lhendup, P., E. Wikramanayake, et al. 2011. <a target="_blank" href="http://www.wwfbhutan.org/?201392/Climate-Change-Vulnerability-Assessment-of-Wangchuck-Centennial-Park">"Climate Change Vulnerability Assessment Of Wangchuck Centennial Park."</a>  Thimphu, Bhutan, World Wildlife Fund.</li>
    <li>Marengo, J. 2012. <a target="_blank" href="http://www.ccafs-climate.org/downloads/docs/marengo_2013_future_cc_projections_latin_america_region.pdf">"Future climate change projections for the Latin American region (from Mexico southwards)."</a> National Institute for Space Research (INPE).</li>
    <li>Monserrate-Rojas, F. 2012. <a target="_blank" href="http://repositorio.usfq.edu.ec/handle/23000/2425">"Modelamiento con el apoyo de Sistemas de Información Geográfico de los efectos de cambio climático sobre parientes silvestres de cultivos prioritarios para la alimentación y la agricultura: Estudio de caso fríjol común."</a> Quito, Ecuador, Universidad San Francisco de Quito.</li>
    <li>Muthoni, F. K. 2010. <a target="_blank" href="http://www.gem-msc.org/Academic%20Output/Academic%20Output%202008/GEM-Francis%20Kamau%20Muthoni-22134.pdf">Modelling the spatial distribution of snake species under changing under changing climate scenario in Spain</a>. MSc. Thesis. University of Twente.</li>
    <li>Ortega-Fernandez, L. A. 2013. <a target="_blank" href="">"Propuesta de sustracción de una porción de la Zona de Reserva Forestal del Pacifico en el muncipio de El Tambo - Cauca."</a>  Convenio de asociación 033 de 2012 entre INCODER y Fundación Ecohabitats. Popayan, Cauca. Convenio de asociación 033 de 2012 entre INCODER y Fundación Ecohabitats. Popayán, Cauca, Fundación Ecohabitats.</li>
    <li>Pérez, J. R. R. and J. E. B. Vargas 2013. <a target="_blank" href="http://revistas.udistrital.edu.co/ojs/index.php/revcie/article/view/5073">"Análisis de escenarios de cambio climático A1B, A2 y B1 para la reserva forestal protectora bosque oriental de Bogotá años 2040, 2070 y 2095 utilizando MarksimGCM: 167-185."</a> </li>
    <li>Platts PJ. 2012. <a target="_blank" href="">"Spatial Modelling, Phytogeography and Conservation in the Eastern Arc Mountains of Tanzania and Kenya"</a> PhD Thesis, University of York, UK</li>
    <li>Platts, P. 2012. <a target="_blank" href="http://etheses.whiterose.ac.uk/2766/">"Spatial modelling, phytogeography and conservation in the Eastern Arc Mountains of Tanzania and Kenya"</a>  University of York, UK</li>
    <li>Platts, P. J., M. Poudyal, et al. 2010. <a target="_blank" href="http://www.york.ac.uk/media/environment/documents/kite/INNOVKAR_WP2_UOY_Report2010.pdf">"Modelling Shea under Climate Scenarios."</a>  University of York, UK, Report for INNOVKAR Work Package 2.</li>
    <li>Rawlings, M., C. Lacambra, et al. 2012. <a target="_blank" href="http://www.worldbank.org/content/dam/Worldbank/document/LAC/Climate%20Change%20Adaptation%20Planning%20for%20Cusco_FINAL.pdf">"Climate Change Adaptation Planning in Latin American and Caribbean Cities Complete Report."</a>  Cusco, Peru, ICF GHK.</li>
    <li>Rosenmund, A. S. 2012. <a target="_blank" href="http://air.unimi.it/bitstream/2434/170257/2/phd_unimi_R08121.pdf">"An integrated modelling framework for climate change impact assessment on rice production and evaluation of adaptation strategies."</a>  A case study in Mali, Università degli Studi di Milano.</li>
    <li>Salvacion, A. R. 2013. <a target="_blank" href="http://cpaf.uplb.edu.ph/">"Estimating Spatio-Temporal Impact of Climate Change on Corn in the Philippines."</a>  College of Public Affairs and Development, University of the Philippines Los Baños.</li>
    <li>Sepo Hachigonta, Gerald Nelson, Timothy S. Thomas, and Lindiwe Majele Sibanda, ed. 2013.  <a target="_blank" href="http://econpapers.repec.org/RePEc:fpr:ifprib:9780896292086">"Southern African Agriculture and Climate Change: A Comprehensive Analysis."</a>  IFPRI Research Monograph. International Food Policy Research Institute (IFPRI). </li>
    <li>Soteriades, A. D. 2011. <a target="_blank" href="http://www.sruc.ac.uk/asoteriades">"Assessing potential environmental shifts under climate change and their implications on agriculture."</a>  College of Science and Engineering, School of GeoSciences. Edinburgh, University of Edinburgh. MSc Dissertation.</li>
    <li>Soteriades, A.D., 2011. <a target="_blank" href="">"Assessing potential environmental shifts under climate change and their implications on agriculture."</a> MSc Dissertation, University of Edinburgh, College of Science and Engineering, School of GeoSciences.</li>
    <li>Thomas, Timothy, Khandaker Mainuddin, Catherine Chiang, Aminur Rahman, Anwarul Haque, Nazria Islam, Saad Quasem, and Yan Sun. 2013. <a target="_blank" href="http://papers.ssrn.com/sol3/papers.cfm?abstract_id=2310087">"Agriculture and Adaptation in Bangladesh: Current and Projected Impacts of Climate Change "</a> IFPRI Discussion Paper 01281 (July). Washington: IFPRI. Available at IFPRI.org.</li>
    <li>Thomas, Timothy, Tin Ponlok, Ros Bansok, Thanakvaro De Lopez, Cathy Chiang, Nang Phirun, and Chhim Chhun. 2013. <a target="_blank" href="http://www.ifpri.org/sites/default/files/publications/ifpridp01285.pdf">"Cambodian Agriculture: Adaptation to Climate Change Impact"</a> IFPRI Discussion Paper 01285 (August). Washington: IFPRI. Available at IFPRI.org.</li>
    <li>Waithaka, Michael, Gerald C Nelson, Timothy S Thomas, Miriam Kyotalimye, Michael Waithaka, and Gerald C Nelson. 2013.  <a target="_blank" href="http://www.ifpri.org/sites/default/files/publications/ib76.pdf">"East African Agriculture and Climate Change: A Comprehensive Analysis"</a> IFPRI Research Monograph. Washington: International Food Policy Research Institute.</li>
    <li>Zomer, R., Trabucco, A., Metzger, M., Oli, K. 2013. <a target="_blank" href="http://lib.icimod.org/record/28328/files/WP_13-1.pdf">"Environmental Stratification of Kailash Sacred Landscape and Projected Climate Change Impacts on Ecosystems and Productivity. Working Paper.(ICIMOD), Kathmandu, Nepal."</a>  International Centre for Integrated Mountain Development </li>
  </ol>

</div>
{include file='footer.tpl'}