{include file='head.tpl' jsIncludes=[] pageTitle="Citations - CCAFS Climate" pageDescription="Peer-reviewed literature that have cited the CCAFS downscaled climate datasets." keywords="CCAFS,literature,citations,climate change,impacts"}
{include file='header.tpl' current="citations"}
<div id="subheader-image">
  <img src="{$smarty.const.SMARTY_IMG_URI}/ribbon_header_citations.gif" />
</div>
<div id="content" class="citations">
  <h3>Citations of our data</h3>
  <hr>
  <br>
  <h4>The following publications have cited our data:</h4>

  <h5>Peer-reviewed articles</h5>
  
  <h5>2015</h5>
  <ol> 
	<li> Crespo-Pérez, Verónica, Jacques Régnière, Isabelle Chuine, François Rebaudo, and Olivier Dangles. 2015. <a target="_blank" href="http://www.ncbi.nlm.nih.gov/pubmed/24920187">"Changes in the Distribution of Multispecies Pest Assemblages Affect Levels of Crop Damage in Warming Tropical Andes."</a> Global Change Biology 21 (1): 82–96. doi:10.1111/gcb.12656.</li>
	<li> Fitzpatrick, Matthew C., and Stephen R. Keller. 2015. <a target="_blank" href="http://onlinelibrary.wiley.com/doi/10.1111/ele.12376/abstract">"Ecological Genomics Meets Community-Level Modelling of Biodiversity: Mapping the Genomic Landscape of Current and Future Environmental Adaptation."</a> Ecology Letters 18 (1): 1–16. doi:10.1111/ele.12376.</li>
	<li> Geismar, J, P Haase, and C Nowak. 2015. <a target="_blank" href="http://onlinelibrary.wiley.com/doi/10.1111/fwb.12489/full ">"Local Population Genetic Structure of the Montane Caddisfly Drusus Discolor Is Driven by Overland Dispersal and Spatial Scaling."</a> Freshwater … 60 (1): 209–21. doi:10.1111/fwb.12489.</li>
	<li> Mestre, F, R Pita, J Paupério, and FMS Martins. 2015. <a target="_blank" href="http://www.sciencedirect.com/science/article/pii/S0304380014005912 ">"Combining Distribution Modelling and Non-Invasive Genetics to Improve Range Shift Forecasting."</a> Ecological Modelling 297: 171–79. doi:10.1016/j.ecolmodel.2014.11.018.</li>
	<li> Pletterbauer, F, AH Melcher, T Ferreira, and S Schmutz. 2015. <a target="_blank" href="http://link.springer.com/article/10.1007/s10750-014-2079-y ">"Impact of Climate Change on the Structure of Fish Assemblages in European Rivers."</a> Hydrobiologia 744 (1): 235–54. doi:10.1007/s10750-014-2079-y.</li>
	<li> Roques, L, JP Rossi, and H Berestycki. 2015. <a target="_blank" href="http://link.springer.com/chapter/10.1007/978-94-017-9340-7_5 ">"Modeling the Spatio-Temporal Dynamics of the Pine Processionary Moth."</a> Processionary Moths and Climate Change, 227–63. doi:10.1007/978-94-017-9340-7_5.</li>
	<li> Sesink Clee, Paul R, Ekwoge E Abwe, Ruffin D Ambahe, Nicola M Anthony, Roger Fotso, Sabrina Locatelli, Fiona Maisels, et al. 2015. <a target="_blank" href="http://www.biomedcentral.com/1471-2148/15/2">"Chimpanzee Population Structure in Cameroon and Nigeria Is Associated with Habitat Variation That May Be Lost under Climate Change."</a> BMC Evolutionary Biology 15 (1): 2.</li>
  </ol> 
  
  <h5>2014</h5>
  <ol>    
	<li> Aguirre‐Gutiérrez, J. 2014. <a target="_blank" href="http://onlinelibrary.wiley.com/doi/10.1111/ddi.12268/full">"Similar but Not Equivalent: Ecological Niche Comparison across Closely–related Mexican White Pines."</a> Diversity and Distributions. doi:10.1111/ddi.12268.</li>
	<li> Alba‐Sánchez, F. 2014. <a target="_blank" href="http://onlinelibrary.wiley.com/doi/10.1111/avsc.12133/full">"Long‐term Climate Forcings to Assess Vulnerability in North Africa Dry Argan Woodlands."</a> Applied Vegetation Science. doi:10.1111/avsc.12133.</li>
	<li> Allen, JL, S Clusella-Trullas, and SL Chown. 2014. <a target="_blank" href="http://link.springer.com/article/10.1007/s10526-014-9570-2">"Thermal Tolerance of Cyrtobagous Salviniae: A Biocontrol Agent in a Changing World."</a> BioControl. doi:10.1007/s10526-014-9570-2.</li>
	<li> Baca, M, P Läderach, J Haggar, G Schroth, and O Ovalle. 2014. <a target="_blank" href="http://dx.plos.org/10.1371/journal.pone.0088463.g007">"An Integrated Framework for Assessing Vulnerability to Climate Change and Developing Adaptation Strategies for Coffee Growing Families in Mesoamerica."</a> PloS One. doi:10.1371/journal.pone.0088463.</li>
	<li> Beatty, GE, L Barker, and PP Chen. 2014. <a target="_blank" href="http://aob.oxfordjournals.org/content/early/2014/12/02/aob.mcu226.short">"Cryptic Introgression into the Kidney Saxifrage (Saxifraga Hirsuta) from Its More Abundant Sympatric Congener Saxifraga Spathularis, and the Potential Risk of Genetic."</a> Annals of Botany. doi:10.1093/aob/mcu226.</li>
	<li> Beaumont, LJ. 2014. <a target="_blank" href="http://onlinelibrary.wiley.com/doi/10.1111/ddi.12190/full">"How Can Knowledge of the Climate Niche Inform the Weed Risk Assessment Process? A Case Study of Chrysanthemoides Monilifera in Australia."</a> Diversity and Distributions 20: 613–25. doi:10.1111/ddi.12190.</li>
	<li> Bellard, C, and C Leclerc. 2014. <a target="_blank" href="http://onlinelibrary.wiley.com/doi/10.1111/geb.12228/full">"Vulnerability of Biodiversity Hotspots to Global Change."</a> Global Ecology and Biogeography 23: 1376–86. doi:10.1111/geb.12228.</li>
	<li> Bellon, MR, and J van Etten. 2014. <a target="_blank" href="http://www.bioversityinternational.org/uploads/tx_news/Climate_change_and_on-farm_conservation_of_crop_landraces_in_centres_of_diversity_1847.pdf">"Climate Change and On-Farm Conservation of Crop Landraces in Centres of Diversity."</a> Plant Genetic Resources and Climate Change.</li>
	<li> Blümmel, M, and A Haileslassie. 2014. <a target="_blank" href="http://www.publish.csiro.au/nid/72/paper/AN14607.htm">"Livestock Water Productivity: Feed Resourcing, Feeding and Coupled Feed-Water Resource Data Bases."</a> Animal Production Science 54 (10): 1584–93.</li>
	<li> Boeckmann, M, and TA Joyner. 2014. <a target="_blank" href="http://www.sciencedirect.com/science/article/pii/S135382921400121X">"Old Health Risks in New Places? An Ecological Niche Model for I. Ricinus Tick Distribution in Europe under a Changing Climate."</a> Health & Place 30: 70–77. doi:10.1016/j.healthplace.2014.08.004.</li>
	<li> Bowman, David M. J. S., Grant J. Williamson, R. J. Keenan, and Lynda D. Prior. 2014. <a target="_blank" href="http://onlinelibrary.wiley.com/doi/10.1111/geb.12171/full">"A Warmer World Will Reduce Tree Growth in Evergreen Broadleaf Forests: Evidence from Australian Temperate and Subtropical Eucalypt Forests."</a> Global Ecology and Biogeography 23 (8): 925–34. doi:10.1111/geb.12171.</li>
	<li> Bunn, C, P Läderach, OO Rivera, and D Kirschke. 2014. <a target="_blank" href="http://link.springer.com/article/10.1007/s10584-014-1306-x">"A Bitter Cup: Climate Change Profile of Global Production of Arabica and Robusta Coffee."</a> Climatic Change. doi:10.1007/s10584-014-1306-x.</li>
	<li> Bystriakova, N, and SW Ansell. 2014. <a target="_blank" href="http://aob.oxfordjournals.org/content/113/3/453.short">"Present, Past and Future of the European Rock Fern Asplenium Fontanum: Combining Distribution Modelling and Population Genetics to Study the Effect of Climate Change."</a> Annals of Botany 113 (3): 453–65. doi:10.1093/aob/mct274.</li>
	<li> Capinha, C, J Rocha, and CA Sousa. 2014. <a target="_blank" href="http://link.springer.com/article/10.1007/s10393-014-0918-y">"Macroclimate Determines the Global Range Limit of Aedes Aegypti."</a> EcoHealth 11 (3): 420–28. doi:10.1007/s10393-014-0918-y.</li>
	<li> Cardoso-Leite, R. 2014. <a target="_blank" href="http://trstmh.oxfordjournals.org/content/108/2/99.short">"Recent and Future Environmental Suitability to Dengue Fever in Brazil Using Species Distribution Model."</a> Transactions of the Royal Society of Tropical Medicine and Hygiene 108 (2): 99–104. doi:10.1093/trstmh/trt115.</li>
	<li> Chandramowli, SN, and FA Felder. 2014. <a target="_blank" href="http://www.sciencedirect.com/science/article/pii/S2213138813000805">"Impact of Climate Change on Electricity Systems and markets–A Review of Models and Forecasts."</a> Sustainable Energy Technologies and Assessments 5: 62–74. doi:10.1016/j.seta.2013.11.003.</li>
	<li> Chapman, DS, T Haynes, and S Beal. 2014. <a target="_blank" href="http://onlinelibrary.wiley.com/doi/10.1111/gcb.12380/full">"Phenology Predicts the Native and Invasive Range Limits of Common Ragweed."</a> Global Change Biology 20 (1): 192–202. doi:10.1111/gcb.12380.</li>
	<li> Chung, U, and S Gbegbelegbe. 2014. <a target="_blank" href="http://www.sciencedirect.com/science/article/pii/S2212094714000668">"Modeling the Effect of a Heat Wave on Maize Production in the USA and Its Implications on Food Security in the Developing World."</a> Weather and Climate Extremes 5-6: 67–77. doi:10.1016/j.wace.2014.07.002.</li>
	<li> Cordovez, JM, LM Rendon, C Gonzalez, and F Guhl. 2014. <a target="_blank" href="http://www.sciencedirect.com/science/article/pii/S0001706X13002775">"Using the Basic Reproduction Number to Assess the Effects of Climate Change in the Risk of Chagas Disease Transmission in Colombia."</a> Acta Tropica 129: 74–82.</li>
	<li> Crego, RD. 2014. <a target="_blank" href="http://journals.cambridge.org/abstract_S037689291300026X">"Climate Change and Conservation Implications for Wet Meadows in Dry Patagonia."</a> Environmental Conservation 41 (2): 122–31. doi:http://dx.doi.org/10.1017/S037689291300026X.</li>
	<li> Cuyckens, GAE, MM Morales, and MF Tognelli. 2014. <a target="_blank" href="http://journals.cambridge.org/production/action/cjoGetFulltext?fulltextid=9374632">"Assessing the Distribution of a Vulnerable Felid Species: Threats from Human Land Use and Climate Change to the Kodkod Leopardus Guigna."</a> Oryx 1: 1–8. doi:10.1017/S003060531300135X.</li>
	<li> Drake, JM, and JC Beier. 2014. <a target="_blank" href="http://www.malariajournal.com/content/13/1/213/abstract">"Ecological Niche and Potential Distribution of Anopheles Arabiensis in Africa in 2050."</a> Malaria Journal 13. doi:10.1186/1475-2875-13-213.</li>
	<li> Eitzinger, A, P Läderach, and C Bunn. 2014. <a target="_blank" href="http://link.springer.com/article/10.1007/s11027-012-9432-0">"Implications of a Changing Climate on Food Security and Smallholders’ Livelihoods in Bogotá, Colombia."</a> Mitigation and Adaptation Strategies for Global Change 19 (2): 161–76. doi:10.1007/s11027-012-9432-0.</li>
	<li> Eriyagama, N, Y Chemin, and R Alankara. 2014. <a target="_blank" href="http://www.iwaponline.com/jwc/005/jwc0050128.htm">"A Methodology for Quantifying Global Consumptive Water Use of Coffee for Sustainable Production under Conditions of Climate Change."</a> Journal of Water and Climate Change 5 (2): 128–50. doi:10.2166/wcc.2013.035.</li>
	<li> Fand, BB, HEZ Tonnang, M Kumar, and SK Bal. 2014. <a target="_blank" href="http://www.sciencedirect.com/science/article/pii/S0304380014002671">"Predicting the Impact of Climate Change on Regional and Seasonal Abundance of the Mealybug Phenacoccus Solenopsis Tinsley (Hemiptera: Pseudococcidae) Using."</a> Ecological Modelling 288: 62–78. doi:10.1016/j.ecolmodel.2014.05.018.</li>
	<li> Feng, S., Q. Hu, et al. 2014. <a target="_blank" href="http://www.sciencedirect.com/science/article/pii/S0921818113002403">"Projected climate regime shift under future global warming from multi-model, multi-scenario CMIP5 simulations."</a> Global and Planetary Change 112: 41-52.</li>
	<li> Ferro, VG, P Lemes, AS Melo, and R Loyola. 2014. <a target="_blank" href="http://dx.plos.org/10.1371/journal.pone.0107792">"The Reduced Effectiveness of Protected Areas under Climate Change Threatens Atlantic Forest Tiger Moths."</a> PloS One 9 (9). doi:10.1371/journal.pone.0107792.</li>
	<li> Fraga, H, and AC Malheiro. 2014. <a target="_blank" href="http://link.springer.com/article/10.1007/s10113-013-0490-y">"Very High Resolution Bioclimatic Zoning of Portuguese Wine Regions: Present and Future Scenarios."</a> Regional Environmental Change 14 (1): 295–306. doi:10.1007/s10113-013-0490-y.</li>
	<li> Giles, JR, AT Peterson, and JD Busch. 2014. <a target="_blank" href="http://www.biomedcentral.com/content/pdf/1756-3305-7-189.pdf">"Invasive Potential of Cattle Fever Ticks in the Southern United States."</a> Parasit & Vectors 7: 1–11.</li>
	<li> Gizachew, L, and A Shimelis. 2014. <a target="_blank" href="http://www.ajol.info/index.php/acsj/article/view/108463">"Analysis and Mapping of Climate Change Risk and Vulnerability in Central Rift Valley of Ethiopia."</a> African Crop Science Journal 22 (4): 807–18.</li>
	<li> González, C, A Paz, and C Ferro. 2014. <a target="_blank" href="http://www.sciencedirect.com/science/article/pii/S0001706X13002192">"Predicted Altitudinal Shifts and Reduced Spatial Distribution of Leishmania Infantum Vector Species under Climate Change Scenarios in Colombia."</a> Acta Tropica 129: 83–90. doi:10.1016/j.actatropica.2013.08.014.</li>
	<li> Habel, JC, RK Mulwa, F Gassert, and D Rödder. 2014. <a target="_blank" href="http://www.nature.com/hdy/journal/vaop/ncurrent/full/hdy201415a.html">"Population Signatures of Large-Scale, Long-Term Disjunction and Small-Scale, Short-Term Habitat Fragmentation in an Afromontane Forest Bird."</a> Heredity 113: 205–14. doi:10.1038/hdy.2014.15.</li>
	<li> Harrigan, RJ. 2014. <a target="_blank" href="http://onlinelibrary.wiley.com/doi/10.1111/gcb.12534/full">"A Continental Risk Assessment of West Nile Virus under Climate Change."</a> Global Change Biology 20 (8): 2417–25. doi:10.1111/gcb.12534.</li>
	<li> Heap, MJ, A Culham, J Lenoir, and RG Gavilán. 2014. <a target="_blank" href="http://www.scirp.org/journal/PaperInformation.aspx?paperID=52760">"Can the Iberian Floristic Diversity Withstand Near-Future Climate Change?"</a> Open Journal of Ecology 4: 1089–1101. doi:10.4236/oje.2014.417089.</li>
	<li> Heit, G, A Iribarne, and W Sione. 2014. <a target="_blank" href="http://www.scielo.cl/scielo.php?pid=S0717-92002014000200012&script=sci_arttext">"Análisis Espacial Del Riesgo de Establecimiento de Lymantria Dispar En Bosques Nativos de Sudamérica."</a> Bosque (Valdivia) 35 (2). doi:http://dx.doi.org/10.4067/S0717-92002014000200012.</li>
	<li> Homburg, K, P Brandt, C Drees, and T Assmann. 2014. <a target="_blank" href="http://link.springer.com/article/10.1007/s10841-014-9685-x">"Evolutionarily Significant Units in a Flightless Ground Beetle Show Different Climate Niches and High Extinction Risk due to Climate Change."</a> Journal of Insect Conservation 18 (5): 781–90. doi:10.1007/s10841-014-9685-x.</li>
	<li> Ikeda, DH, KC Grady, SM Shuster, and TG Whitham. 2014. <a target="_blank" href="http://dx.plos.org/10.1371/journal.pone.0107037">"Incorporating Climate Change and Exotic Species into Forecasts of Riparian Forest Distribution."</a> PloS One 9 (9). doi:10.1371/journal.pone.0107037.</li>
	<li> Jones, MR, A Singels, and A Ruane. 2014. <a target="_blank" href="http://www.sasta.co.za/wp-content/uploads/Proceedings/2010s/2013-22Jones.pdf">"Simulated Impacts of Climate Change on Water Use and Yield of Irrigated Sugarcane in South Africa."</a> SHORT NON-REFEREED PAPER 86: 184–89.</li>
	<li> Kaspari, M, and NA Clay. 2014. <a target="_blank" href="http://onlinelibrary.wiley.com/doi/10.1111/gcb.12750/full">"Thermal Adaptation Generates a Diversity of Thermal Limits in a Rainforest Ant Community."</a> Global Change Biology. doi:10.1111/gcb.12750.</li>
	<li> Kelly, R, and K Leach. 2014. <a target="_blank" href="http://onlinelibrary.wiley.com/doi/10.1111/ddi.12194/full">"Combining Global Climate and Regional Landscape Models to Improve Prediction of Invasion Risk."</a> Diversity and Distributions 20 (8): 884–94. doi:10.1111/ddi.12194.</li>
	<li> Khadioli, N, and ZEH Tonnang. 2014. <a target="_blank" href="http://journals.cambridge.org/abstract_S0007485314000601">"Effect of Temperature on the Phenology of Chilo Partellus (Swinhoe)(Lepidoptera, Crambidae); Simulation and Visualization of the Potential Future Distribution of C."</a> Bulletin of Entomological Research 104 (6): 809–22. doi:http://dx.doi.org/10.1017/S0007485314000601.</li>
	<li> Kolanowska, M, and K Konowalik. 2014. <a target="_blank" href="http://onlinelibrary.wiley.com/doi/10.1111/btp.12089/full">"Niche Conservatism and Future Changes in the Potential Area Coverage of Arundina Graminifolia, an Invasive Orchid Species from Southeast Asia."</a> Biotropica 46 (2): 157–65. doi:10.1111/btp.12089.</li>
	<li> Kuntner, M, M Năpăruş, D Li, and JA Coddington. 2014. <a target="_blank" href="http://dx.plos.org/10.1371/journal.pone.0098907">"Phylogeny Predicts Future Habitat Shifts Due to Climate Change."</a> PloS One 9 (6). doi:10.1371/journal.pone.0098907.</li>
	<li> Leroy, B, C Bellard, and N Dubos. 2014. <a target="_blank" href="http://onlinelibrary.wiley.com/doi/10.1111/ddi.12191/full">"Forecasted Climate and Land Use Changes, and Protected Areas: The Contrasting Case of Spiders."</a> Diversity and Distributions 20 (6): 686–97. doi:10.1111/ddi.12191.</li>
	<li> Lopez, A, EB Suckling, and LA Smith. 2014. <a target="_blank" href="http://link.springer.com/article/10.1007/s10584-013-1022-y">"Robustness of Pattern Scaled Climate Change Scenarios for Adaptation Decision Support."</a> Climatic Change 122 (4): 555–66. doi:10.1007/s10584-013-1022-y.</li>
	<li> Loyola, RD, P Lemes, and FT Brum. 2014. <a target="_blank" href="http://onlinelibrary.wiley.com/doi/10.1111/j.1600-0587.2013.00396.x/full">"Clade‐specific Consequences of Climate Change to Amphibians in Atlantic Forest Protected Areas."</a> Ecography 37 (1): 65–72. doi:10.1111/j.1600-0587.2013.00396.x.</li>
	<li> Lyu, N, and YH Sun. 2014. <a target="_blank" href="http://www.bioone.org/doi/abs/10.2981/wlb.13024">"Predicting Threat of Climate Change to the Chinese Grouse on the Qinghai-Tibet Plateau."</a> Wildlife Biology 20 (2): 73–82. doi:http://dx.doi.org/10.2981/wlb.13024.</li>
	<li> Mancosu, E, and A Gago-Silva. 2014. <a target="_blank" href="http://www.sciencedirect.com/science/article/pii/S1462901114000550">"Future Land-Use Change Scenarios for the Black Sea Catchment."</a> Environmental Science & Policy 46: 26–36. doi:10.1016/j.envsci.2014.02.008.</li>
	<li> Manthey, JD, J Klicka, and GM Spellman. 2014. <a target="_blank" href="http://www.aoucospubs.org/doi/abs/10.1642/AUK-13-242.1">"Effects of Climate Change on the Evolution of Brown Creeper (Certhia Americana) Lineages."</a> The Auk 131 (4): 559–70. doi:http://dx.doi.org/10.1642/AUK-13-242.1.</li>
	<li> Markovic, D, S Carrizo, and J Freyhof. 2014. <a target="_blank" href="http://onlinelibrary.wiley.com/doi/10.1111/ddi.12232/full">"Europe’s Freshwater Biodiversity under Climate Change: Distribution Shifts and Conservation Needs."</a> Diversity and Distributions 20 (9): 1097–1107. doi:10.1111/ddi.12232.</li>
	<li> Martins, AC, and DP Silva. 2014. <a target="_blank" href="http://link.springer.com/article/10.1007/s10841-014-9740-7">"Species Conservation under Future Climate Change: The Case of Bombus Bellicosus, a Potentially Threatened South American Bumblebee Species."</a> Journal of Insect Conservation. doi:10.1007/s10841-014-9740-7.</li>
	<li> Mazur, MLC, KP Kowalski, and D Galbraith. 2014. <a target="_blank" href="http://www.aquaticinvasions.net/2014/AI_2014_CarlsonMazur_etal.pdf">"Assessment of Suitable Habitat for Phragmites Australis (common Reed) in the Great Lakes Coastal Zone."</a> Aquatic Invasions 9 (1): 1–19. doi:http://dx.doi.org/10.3391/ai.2014.9.1.01.</li>
	<li> Molloy, SW. 2014. <a target="_blank" href="http://journals.cambridge.org/abstract_S0376892913000337">"Species Distribution Modelling Using Bioclimatic Variables to Determine the Impacts of a Changing Climate on the Western Ringtail Possum ( Pseudocheirus."</a> Environmental Conservation 41 (1): 176–86. doi:http://dx.doi.org/10.1017/S0376892913000337.</li>
	<li> Nori, J, PA Carrasco, and GC Leynaud. 2014. <a target="_blank" href="http://link.springer.com/article/10.1007/s10584-013-1019-6">"Venomous Snakes and Climate Change: Ophidism as a Dynamic Problem."</a> Climatic Change 122 (1-2): 67–80. doi:10.1007/s10584-013-1019-6.</li>
	<li> Nyairo R, Onwonga R, Cherogony K, Luedeling E. 2014. <a target="_blank" href="http://www.ccsenet.org/journal/index.php/sar/article/view/38493.">"Applicability of Climate Analogues for Climate Change Adaptation Planning in Bugabira Commune of Burundi.Sustainable Agriculture Research 3 (4): p46. doi:10.5539/sar.v3n4p46.
	<li> Oakgrove, KS, RJ Harrigan, and C Loiseau. 2014. <a target="_blank" href="http://www.sciencedirect.com/science/article/pii/S0020751914001465">"Distribution, Diversity and Drivers of Blood-Borne Parasite Co-Infections in Alaskan Bird Populations."</a> International Journal for Parasitology 44 (10): 717–27. doi:10.1016/j.ijpara.2014.04.011.</li>
	<li> Oliveira, RS, and CB Eller. 2014. <a target="_blank" href="http://aob.oxfordjournals.org/content/113/6/909.short">"The Hydroclimatic and Ecophysiological Basis of Cloud Forest Distributions under Current and Projected Climates."</a> Annals of Botany 113 (6): 909–20. doi:10.1093/aob/mcu060.</li>
	<li> Ortíz-Yusty, C, A Restrepo, and VP Páez. 2014. <a target="_blank" href="http://www.scielo.org.co/scielo.php?pid=S0120-548X2014000300013&script=sci_arttext">"Potential Distribution of Podocnemis Lewyana (Reptilia: Podocnemididae) and Its Possible Fluctuation Under Different Global Climate Change Scenarios."</a> Acta Biológica Colombiana 19 (3). doi:http://dx.doi.org/10.15446/abc.v19n3.40909.</li>
	<li> Ortíz-Yusty, Carlos; Adriana Restrepo; Vivian P. Páez. 2014. <a target="_blank" href="http://www.scielo.org.co/pdf/abc/v19n3/v19n3a13.pdf">"DISTRIBUCIÓN POTENCIAL DE Podocnemis Lewyana (REPTILIA: PODOCNEMIDIDAE) Y SU POSIBLE FLUCTUACIÓN BAJO ESCENARIOS DE CAMBIO."</a> Acta Biológica Colombiana 19 (3): 471–81.</li>
	<li> Paingankar, MS, and MD Gokhale. 2014. <a target="_blank" href="http://www.researchgate.net/profile/Mandar_Paingankar/publication/263061039_Monitoring_of_dengue_and_chikungunya_viruses_in_field_caught_Aedes_aegypti_(Diptera_Culicidae)_in_Surat_city_India/links/0a85e53acc6aad6a1c000000.pdf">"Surat City, India."</a> CURRENT SCIENCE 106 (11): 1559–67.</li>
	<li> Parajuli, K, and K Kang. 2014. <a target="_blank" href="http://link.springer.com/article/10.3103/S1068373914040086">"Application of Statistical Downscaling in GCMs at Constructing the Map of Precipitation in the Mekong River Basin."</a> Russian Meteorology and Hydrology 39 (4): 271–82. doi:10.3103/S1068373914040086.</li>
	<li> Peers, MJL, and M Wehtje. 2014. <a target="_blank" href="http://onlinelibrary.wiley.com/doi/10.1111/gcb.12469/full">"Prey Switching as a Means of Enhancing Persistence in Predators at the Trailing Southern Edge."</a> Global Change Biology 20 (4): 1126–35. doi:10.1111/gcb.12469.</li>
	<li> Pérez‐Rodríguez, A. 2014. <a target="_blank" href="http://onlinelibrary.wiley.com/doi/10.1111/gcb.12542/full">"Global Warming Will Reshuffle the Areas of High Prevalence and Richness of Three Genera of Avian Blood Parasites."</a> Global Change Biology 20 (8): 2406–16. doi:10.1111/gcb.12542.</li>
	<li> Perktaş, U, H Gür, İK Sağlam, and E Quintero. 2014. <a target="_blank" href="http://www.tandfonline.com/doi/abs/10.1080/00063657.2014.977220">"Climate-Driven Range Shifts and Demographic Events over the History of Kruper’s Nuthatch Sitta Krueperi."</a> Bird Study 62 (1): 14–28.</li>
	<li> Platts, PJ, PA Omeny, and R Marchant. 2014. <a target="_blank" href="http://onlinelibrary.wiley.com/doi/10.1111/aje.12180/full">"AFRICLIM: High‐resolution Climate Projections for Ecological Applications in Africa."</a> African Journal of Ecology. doi:10.1111/aje.12180.</li>
	<li> Pliscoff, P, F Luebert, HH Hilger, and A Guisan. 2014. <a target="_blank" href="http://www.sciencedirect.com/science/article/pii/S0304380014002713">"Effects of Alternative Sets of Climatic Predictors on Species Distribution Models and Associated Estimates of Extinction Risk: A Test with Plants in an Arid Environment."</a> Ecological Modelling 288: 166–77. doi:10.1016/j.ecolmodel.2014.06.003.</li>
	<li> Posada-Suárez, H, and P Läderach. 2014. <a target="_blank" href="http://dx.plos.org/10.1371/journal.pone.0113510.g002">"Recommendations for the Regionalizing of Coffee Cultivation in Colombia: A Methodological Proposal Based on Agro-Climatic Indices."</a> PloS One 9 (12). doi:10.1371/journal.pone.0113510.</li>
	<li> Poudel, RC, M Möller, and J Liu. 2014. <a target="_blank" href="http://onlinelibrary.wiley.com/doi/10.1111/ddi.12237/full">"Low Genetic Diversity and High Inbreeding of the Endangered Yews in Central Himalaya: Implications for Conservation of Their Highly Fragmented Populations."</a> Diversity and Distributions 20 (1): 1270–84. doi:10.1111/ddi.12237.</li>
	<li> Ramírez-Villegas, J, and F Cuesta. 2014. <a target="_blank" href="http://www.sciencedirect.com/science/article/pii/S1617138114000387">"Using Species Distributions Models for Designing Conservation Strategies of Tropical Andean Biodiversity under Climate Change."</a> Journal for Nature Conservation 22 (5): 391–404. doi:10.1016/j.jnc.2014.03.007.</li>
	<li> Remesan, R, T Bellerby, and L Frostick. 2014. <a target="_blank" href="http://onlinelibrary.wiley.com/doi/10.1002/hyp.9872/full">"Hydrological Modelling Using Data from Monthly GCMs in a Regional Catchment."</a> Hydrological Processes 28 (8): 3241–63. doi:10.1002/hyp.9872.</li>
	<li> Riordan, EC, and PW Rundel. 2014. <a target="_blank" href="http://dx.plos.org/10.1371/journal.pone.0086487">"Land Use Compounds Habitat Losses under Projected Climate Change in a Threatened California Ecosystem."</a> PloS One 9 (1). doi:10.1371/journal.pone.0086487.</li>
	<li> Robinet, C, J Rousselet, and A Roques. 2014. <a target="_blank" href="http://link.springer.com/article/10.1007/s13595-013-0287-7">"Potential Spread of the Pine Processionary Moth in France: Preliminary Results from a Simulation Model and Future Challenges."</a> Annals of Forest Science 71 (2): 149–60. doi:10.1007/s13595-013-0287-7.</li>
	<li> Rocha, J, RA da Silva, F Amich, and Á Martins. 2014. <a target="_blank" href="http://revistas.ucm.es/index.php/LAZA/article/view/44196">"Biogeographic Trends of Endemic and Subendemic Flora in the Western Iberian Peninsula under Scenarios of Future Climate Changes."</a> Lazaroa 35: 19–35. doi:10.5209/rev_LAZA.2014.v35.44196.</li>
	<li> Romero-Perezgrovas, R., Verhulst, N., De La Rosa, D., Hernández, V., Maertens, M., Deckers, J. and Govaerts, B. 2014. <a target="_blank" href="http://www.sciencedirect.com/science/article/pii/S1002016014600345.">"Effects of Tillage and Crop Residue Management on Maize Yields and Net Returns in the Central Mexican Highlands Under Drought Conditions."</a> Pedosphere 24 (4): 476–86. doi:10.1016/S1002-0160(14)60034-5.</li>
	<li> Russell, J, M van Zonneveld, and IK Dawson. 2014. <a target="_blank" href="http://dx.plos.org/10.1371/journal.pone.0086021">"Genetic Diversity and Ecological Niche Modelling of Wild Barley: Refugia, Large-Scale Post-LGM Range Expansion and Limited Mid-Future Climate Threats?"</a> PloS One 9 (2). doi:10.1371/journal.pone.0086021.</li>
	<li> Ryan, SJ, A McNally, and LR Johnson. 2014. <a target="_blank" href="http://arxiv.org/abs/1407.7612">"Rising Suitability and Declining Severity of Malaria Transmission in Africa under Climate Change."</a> Cornell University Library. doi:arXiv:1407.7612.</li>
	<li> Sahlean, TC, I Gherghel, and M Papeş. 2014. <a target="_blank" href="http://dx.plos.org/10.1371/journal.pone.0091994.g003">"Refining Climate Change Projections for Organisms with Low Dispersal Abilities: A Case Study of the Caspian Whip Snake."</a> PloS One 9 (3). doi:10.1371/journal.pone.0091994.</li>
	<li> Sánchez-Guillén, RA, and J Munoz. 2014. <a target="_blank" href="http://link.springer.com/article/10.1007/s10841-014-9637-5">"Hybridization Rate and Climate Change: Are Endangered Species at Risk?"</a> Journal of Insect Conservation 18 (3): 295–305. doi:10.1007/s10841-014-9637-5.</li>
	<li> Santos, X, M Vidal-García, and JC Brito. 2014. <a target="_blank" href="http://link.springer.com/article/10.1007/s10682-014-9699-6">"Phylogeographic and Environmental Correlates Support the Cryptic Function of the Zigzag Pattern in a European Viper."</a> Evolutionary Ecology 28 (4): 611–26. doi:10.1007/s10682-014-9699-6.</li>
	<li> Schaad, DA, F Pulido, and JAL Sáez. 2014. <a target="_blank" href="http://revistas.ucm.es/index.php/LAZA/article/view/41932">"Persistence of Tree Relicts in the Spanish Central System through the Holocene."</a> Lazaroa 35: 107–31. doi:10.5209/rev_LAZA.2014.v35.41932.</li>
	<li> Schmitt, T, and JC Habel. 2014. <a target="_blank" href="http://onlinelibrary.wiley.com/doi/10.1111/gcb.12462/full">"Effects of Recent and Past Climatic Shifts on the Genetic Structure of the High Mountain Yellow‐spotted Ringlet Butterfly Erebia Manto (Lepidoptera, Satyrinae): A."</a> Global Change Biology 20 (7): 2045–61. doi:10.1111/gcb.12462.</li>
	<li> Schroth, G, P Läderach, and DSB Cuero. 2014. <a target="_blank" href="http://link.springer.com/article/10.1007/s10113-014-0713-x">"Winner or Loser of Climate Change? A Modeling Study of Current and Future Climatic Suitability of Arabica Coffee in Indonesia."</a> Regional Environmental Change. doi:10.1007/s10113-014-0713-x.</li>
	<li> Sérgio, C, and CA Garcia. 2014. <a target="_blank" href="http://www.tandfonline.com/doi/abs/10.1080/11263504.2014.949329">"Conservation of Portuguese Red-Listed Bryophytes Species in Portugal: Promoting a Shift in Perspective on Climate Changes."</a> Plant Biosystems - An International Journal 148 (4): 837–50. doi:10.1080/11263504.2014.949329.</li>
	<li> Shah, DN, S Domisch, SU Pauls, P Haase, and SC Jähnig. 2014. <a target="_blank" href="http://www.bioone.org/doi/abs/10.1086/678492">"Current and Future Latitudinal Gradients in Stream Macroinvertebrate Richness across North America."</a> Freshwater Science 33 (4): 1136–47. doi:http://dx.doi.org/10.1086/678492.</li>
	<li> Shrestha, UB, and KS Bawa. 2014. <a target="_blank" href="http://dx.plos.org/10.1371/journal.pone.0106405">"Impact of Climate Change on Potential Distribution of Chinese Caterpillar Fungus (Ophiocordyceps Sinensis) in Nepal Himalaya."</a> PloS One 9 (9). doi:10.1371/journal.pone.0106405.</li>
	<li> Silva, RA, J Rocha, A Silva, and I García-Cabral. 2014. <a target="_blank" href="http://www.bioone.org/doi/abs/10.1600/036364414X682544">"The Iberian Species of Scilla (Subfamily Scilloideae, Family Asparagaceae) under Climatic Change Scenarios in Southwestern Europe."</a> Systematic Botany 39 (4): 1083–98. doi:http://dx.doi.org/10.1600/036364414X682544.</li>
	<li> Singh, P, S Nedumaran, and KJ Boote. 2014. <a target="_blank" href="http://www.sciencedirect.com/science/article/pii/S1161030113001391">"Climate Change Impacts and Potential Benefits of Drought and Heat Tolerance in Chickpea in South Asia and East Africa."</a> European Journal of Agronomy 52: 123–37. doi:10.1016/j.eja.2013.09.018.</li>
	<li> Singh, P, S Nedumaran, and BR Ntare. 2014. <a target="_blank" href="http://link.springer.com/article/10.1007/s11027-012-9446-7">"Potential Benefits of Drought and Heat Tolerance in Groundnut for Adaptation to Climate Change in India and West Africa."</a> Mitigation and Adaptation Strategies for Global Change 19 (5): 509–29. doi:10.1007/s11027-012-9446-7.</li>
	<li> Singh, P, S Nedumaran, and PCS Traore. 2014. <a target="_blank" href="http://www.sciencedirect.com/science/article/pii/S0168192313002803">"Quantifying Potential Benefits of Drought and Heat Tolerance in Rainy Season Sorghum for Adapting to Climate Change."</a> Agricultural and Forest Meteorology 185: 37–48. doi:10.1016/j.agrformet.2013.10.012.</li>
	<li> Singh, P, NP Singh, and KJ Boote. 2014. <a target="_blank" href="http://oar.icrisat.org/8463/1/JournalofAgrometeorology_16_1_52-59_2014.pdf">"Management Options to Increase Groundnut Productivity under Climate Change at Selected Sites in India."</a> Journal of Agrometeorology 16 (1): 52–59.</li>
	<li> Soesbergen, AJJ van, and M Mulligan. 2014. <a target="_blank" href="http://www.earth-syst-dynam.net/5/55/2014/esd-5-55-2014.html">"Modelling Multiple Threats to Water Security in the Peruvian Amazon Using the WaterWorld Policy Support System."</a> Earth System Dynamics 5: 55–65. doi:10.5194/esd-5-55-2014.</li>
	<li> Swab, RM, HM Regan, and D Matthies. 2014. <a target="_blank" href="http://onlinelibrary.wiley.com/doi/10.1111/ecog.00585/full">"The Role of Demography, Intra‐species Variation, and Species Distribution Models in Species’ Projections under Climate Change."</a> Ecography. doi:10.1111/ecog.00585.</li>
	<li> Tonini, F, and F Divino. 2014. <a target="_blank" href="http://ee.oxfordjournals.org/content/43/5/1135.abstract">"Predicting the Geographical Distribution of Two Invasive Termite Species from Occurrence Data."</a> Environmental Entomology 1: 1135–44. doi:http://dx.doi.org/10.1603/EN13312.</li>
	<li> Vasconcelos, T da Silveira. 2014. <a target="_blank" href="http://www.sciencedirect.com/science/article/pii/S1679007314500084">"Tracking Climatically Suitable Areas for an Endemic Cerrado Snake under Climate Change."</a> Natureza & Conservação 12 (1): 47–52. doi:10.4322/natcon.2014.009.</li>
	<li> Vásquez-Morales, SG. 2014. <a target="_blank" href="http://www.botanicalsciences.com.mx/index.php/botanicalSciences/article/view/116">"Effect of Climate Change on the Distribution of Magnolia Schiedeana: A Threatened Species."</a> Botanical Sciences 92 (4): 575–85. doi:http://dx.doi.org/10.17129/botsci.116.</li>
	<li> Wan, J, C Wang, J Yu, S Nie, and S Han. 2014. <a target="_blank" href="http://onlinelibrary.wiley.com/doi/10.1002/ece3.1133/full">"Model‐based Conservation Planning of the Genetic Diversity of Phellodendron Amurense Rupr due to Climate Change."</a> Ecology and Evolution 4 (14): 2884–2900. doi:10.1002/ece3.1133.</li>
	<li> Worth, JRP, and PA Harrison. 2014. <a target="_blank" href="http://onlinelibrary.wiley.com/doi/10.1111/aec.12184/full">"Whole Range and Regional‐based Ecological Niche Models Predict Differing Exposure to 21st Century Climate Change in the Key Cool Temperate Rainforest Tree Southern."</a> Austral Ecology. doi:10.1111/aec.12184.</li>
	<li> Xavier Santos, Marta Vidal-García, José C. Brito, Soumia Fahd, Gustavo A. Llorente, Fernando Martínez-Freiría. 2014. <a target="_blank" href="http://www.researchgate.net/profile/Soumia_Fahd2/publication/261637363_Phylogeographic_and_environmental_correlates_support_the_cryptic_function_of_the_zigzag_pattern_in_a_European_viper/links/5417dd9d0cf2f48c74a41485.pdf">"Phylogeographic and Environmental Correlates Support the Cryptic Function of the Zigzag Pattern in a European Viper."</a> Evolutionary Ecology 28 (4): 611–26. doi:DOI 10.1007/s10682-014-9699-6.</li>
	<li> Xu, Z, H Peng, Z Feng, and N Abdulsalih. 2014. <a target="_blank" href="http://www.bioone.org/doi/abs/10.3161/104.062.0207">"Predicting Current and Future Invasion of Solidago Canadensis: A Study from China."</a> Polish Journal of Ecology 62 (2): 263–71. doi:http://dx.doi.org/10.3161/104.062.0207.</li>
	<li> Xue, Z, Z Zhang, X Lu, Y Zou, and Y Lu. 2014. <a target="_blank" href="http://www.sciencedirect.com/science/article/pii/S0921818114002057">"Predicted Areas of Potential Distributions of Alpine Wetlands under Different Scenarios in the Qinghai-Tibetan Plateau, China."</a> Journal of Insect Conservation 123: 77–85. doi:10.1016/j.gloplacha.2014.10.012.</li>
	<li> Ye, L, H Tang, W Wu, and P Yang. 2014. <a target="_blank" href="http://www.econstor.eu/handle/10419/90644">"Chinese Food Security and Climate Change: Agriculture Futures."</a> Economics: The Open-Access, Open-Assessment E-Journal 8 (1): 1–39. doi:10.5018/economics-ejournal.ja.2014-1.</li>
	<li> York, EM, CJ Butler, and WD Lord. 2014. <a target="_blank" href="http://dx.plos.org/10.1371/journal.pone.0103831.g005">"Global Decline in Suitable Habitat for Angiostrongylus (= Parastrongylus) Cantonensis: The Role of Climate Change."</a> PloS One 9 (8). doi:10.1371/journal.pone.0103831.</li>
	<li> Yu, J, J Wan, and C Wang. 2014. <a target="_blank" href="http://www.academicjournals.org/journal/IJBC/article-abstract/0F21D7844261">"Planning the Priority Protected Areas of Chosenia Arbutifolia due to Climate Change in Northeastern China."</a> International Journal of Biodiversity and Conservation 6 (5): 422–27. doi:10.5897/IJBC2013.0661.</li>
	<li> Yu, L, J Wang, XC Li, and CC Li. 2014. <a target="_blank" href="http://link.springer.com/article/10.1007/s11430-014-4919-z">"A Multi-Resolution Global Land Cover Dataset through Multisource Data Aggregation."</a> Science China Earth Sciences 57 (10): 2317–29. doi:10.1007/s11430-014-4919-z.</li>
	<li> Zhang, MG, and ZK Zhou. 2014. <a target="_blank" href="http://onlinelibrary.wiley.com/doi/10.1111/ddi.12165/full">"Major Declines of Woody Plant Species Ranges under Climate Change in Yunnan, China."</a> Diversity and Distributions 20 (4): 405–15. doi:10.1111/ddi.12165.</li>
	<li> Zomer, Robert J, Antonio Trabucco, Mingcheng Wang, Rong Lang, Huafang Chen, Marc J Metzger, Alex Smajgl, Philip Beckschäfer, and Jianchu Xu. 2014. <a target="_blank" href="http://www.sciencedirect.com/science/article/pii/S000632071300414X.">"Environmental Stratification to Model Climate Change Impacts on Biodiversity and Rubber Production in Xishuangbanna, Yunnan, China."</a> Biological Conservation 170 (0): 264–73. doi:http://dx.doi.org/10.1016/j.biocon.2013.11.028.</li>
	<li> 宫鹏俞乐， 王杰， 李雪草， 李丛丛， 赵圆圆，. 2014. <a target="_blank" href="http://earth.scichina.com:8080/sciD/CN/article/downloadArticleFile.do?attachType=PDF&id=515004">"Cover Mapping Based on Multi-Resolution Global Surface Multi-Source Data Integration."</a> Chinese Science: Earth Sciences 44 (8): 1646–60. doi:10.1007/s11430-014-4919-z.</li>
	<li> 崔鹏孙立， 徐海根， 吴军， 雷军成，. 2014. <a target="_blank" href="http://www.ere.ac.cn/EN/article/downloadArticleFile.do?attachType=PDF&id=10751">"Impact of Climate Change on Distribution of Breeding Places of White-Naped Crane in China."</a> Ecology and Rural Environment 30 (5): 595-600.</li>
	<li> 曹坳程王罛， 林慧龙， 何兰，. 2014. <a target="_blank" href="http://cyxb.lzu.edu.cn/fileup/PDF/20140403.pdf">"Eupatorium Potential Distribution of the Response to Climate Change."</a> Grass Industry Journal 23 (4): 20-30.</li>
  </ol>  	

  <h5>2013</h5>
  <ol>
    <li>Byers, J.E., W.G. McDowell, S. Robertson, R. Haynie, L.M. Pintor, and S.B. Wilde. 2013.  <a target="_blank" href="http://dx.doi.org/10.1371/journal.pone.0056812">"Climate and pH predict the spread of the invasive Apple snail (Pomacea insularum) in the southeastern United States."</a> PLoS ONE 8 (2) (February 22): e56812. </li>
    <li>B. Leroy, M. Paschetta, A. Canard, M. Bakkenes, M. Isaia, and F. Ysnel. (2013). <a target="_blank" href="http://www.sciencedirect.com/science/article/pii/S000632071300089X. ">"First assessment of effects of global change on threatened spiders: Potential impacts on Dolomedes plantarius (Clerck) and its conservation plans"</a> Biol. Conserv. 2013;161:155–163.</li>
    <li>Bellard, C., W. Thuiller, et al. 2013. <a target="_blank" href="http://dx.doi.org/10.1111/gcb.12344">"Will climate change promote future invasions? Global Change Biology 19(12): 3740-3748."</a> </li>
    <li>Bucklin, D., J. Watling, et al. 2013. <a target="_blank" href="http://dx.doi.org/10.1007/s10113-012-0389-z">"Climate downscaling effects on predictive ecological models: a case study for threatened and endangered vertebrates in the southeastern United States."</a> Regional Environmental Change 13(1): 57-68.</li>
    <li>Cairns, J., J. Hellin, et al. (2013) <a target="_blank" href="http://rd.springer.com/article/10.1007/s12571-013-0256-x#">"Adapting maize production to climate change in sub-Saharan Africa." </a> Food Security: 1-16. </li>
    <li>Chapman D.S., Haynes T., Beal S., Essl F. & Bullock J.M. (In press). 2013. <a target="_blank" href="http://dx.doi.org/10.1111/gcb.12380">"Phenology Predicts the Native and Invasive Range Limits of Common Ragweed."</a> Global Change Biology: n/a–n/a. doi:10.1111/gcb.12380.</li>
    <li>D’Amen, M., et al. (2013). <a target="_blank" href="http://onlinelibrary.wiley.com/doi/10.1111/j.1466-8238.2012.00774.x/abstract">"Conservation of phylogeographic lineages under climate change."</a> Global Ecology and Biogeography 22(1): 93-104.</li>
    <li>Fandohan B, Gouwakinnou GN, Fonton NH, Sinsin B, Liu J. 2013.  <a target="_blank" href="http://www.pressesagro.be/base/text/v17n3/450.pdf">"Impact Des Changements Climatiques Sur La Répartition Géographique Des Aires Favorables à La Culture et à La Conservation Des Fruitiers Sous-Utilisés : Cas Du Tamarinier Au Bénin"</a> Biotechnology Agronomy Society and Environment 17(3) : 450–462.</li>
    <li>Feng, S. and Q. Fu 2013. <a target="_blank" href="http://www.atmos-chem-phys-discuss.net/13/14637/2013/">"Expansion of global drylands under a warming climate."</a> Atmos. Chem. Phys. Discuss. 13(6): 14637-14665.</li>
    <li>Flavio Lupia, P. N. 2013. <a target="_blank" href="http://www.researchgate.net/publication/245335015_Creazione_di_Geodatabase_per_la_Raccolta_di_Dati_Prodotti_da_Modelli_di_Simulazione_di_Cambiamento_Climatico">"Creazione di Geodatabase per la Raccolta di Dati Prodotti da Modelli di Simulazione di Cambiamento Climatico."</a> </li>
    <li>Gallardo, B. and D.C. Aldridge. 2013.  <a target="_blank" href="http://www.sciencedirect.com/science/article/pii/S0006320713000402">"Evaluating the Combined Threat of Climate Change and Biological Invasions on Endangered Species."</a> Biological Conservation 160 (0) (April): 225–233.</li>
    <li>Giannini T.C., Chapman D.S., Saraiva A.M., Alves-dos-Santos I. & Biesmeijer J.C. 2013.  <a target="_blank" href="http://dx.doi.org/10.1111/j.1600-0587.2012.07191.x ">"Improving Species Distribution Models Using Biotic Interactions: a Case Study of Parasites, Pollinators and Plants."</a> Ecography 36 (6): 649–656. doi:10.1111/j.1600-0587.2012.07191.x. </li>
    <li>Huang, J. G., Y. Bergeron, et al. 2013. <a target="_blank" href="http://www.plosone.org/article/info%3Adoi%2F10.1371%2Fjournal.pone.0056758">"Impact of future climate on radial growth of four major boreal tree species in the Eastern Canadian boreal forest."</a> PloS one 8(2): 28.</li>
    <li>Iwamura, T., A. Guisan, et al. 2013. <a target="_blank" href="http://www.sciencedirect.com/science/article/pii/S0959378013001222">"How robust are global conservation priorities to climate change?"</a> Global Environmental Change 23(5): 1277-1284.</li>
    <li>Kolanowska, M. 2013. <a target="_blank" href="http://europepmc.org/abstract/MED/24143222">"Niche conservatism and the future potential range of Epipactis helleborine (Orchidaceae)."</a> PloS one 8(10): e77352.</li>
    <li>Kroschel, J., M. Sporleder, et al. 2013. <a target="_blank" href="http://dx.doi.org/10.1016/j.agrformet.2012.06.017">"Predicting climate-change-caused changes in global temperature on potato tuber moth Phthorimaea operculella (Zeller) distribution and abundance using phenology modeling and GIS mapping."</a> Agricultural and Forest Meteorology 170(0): 228-241.</li>
    <li>Läderach, P., A. Martinez-Valle, et al. 2013. <a target="_blank" href="http://dx.doi.org/10.1007/s10584-013-0774-8">"Predicting the future climatic suitability for cocoa farming of the world’s leading producer countries, Ghana and Côte d’Ivoire."</a> Climatic Change 119(3-4): 841-854.</li>
    <li>Leroy, B., M. Paschetta, et al. (2013)  <a target="_blank" href="http://www.sciencedirect.com/science/article/pii/S000632071300089X">"First assessment of effects of global change on threatened spiders: Potential impacts on Dolomedes plantarius (Clerck) and its conservation plans." </a> Biological Conservation 161(0): 155-163.</li>
    <li>Machovina, Brian, and Kenneth J Feeley. 2013.  <a target="_blank" href="http://www.sciencedirect.com/science/article/pii/S0921800913002619 ">"Climate Change Driven Shifts in the Extent and Location of Areas Suitable for Export Banana Production."</a> Ecological Economics 95 (0) (November): 83–95.</li>
    <li>Naujokaitis-Lewis, I., J.M.R. Curtis, L. Tischendorf, D. Badzinski, K. Lindsay, M.-J. Fortin. 2013.  <a target="_blank" href="http://dx.doi.org/10.1111/ddi.12063 ">"Uncertainties in Coupled Species Distribution–metapopulation Dynamics Models for Risk Assessments Under Climate Change."</a> Diversity and Distributions 19 (5-6): 541–554. doi:10.1111/ddi.12063. </li>
    <li>Platts PJ, Gereau RE, Burgess ND, Marchant R. 2013.  <a target="_blank" href="http://dx.doi.org/10.1111/j.1600-0587.2012.07805.x">"Spatial Heterogeneity of Climate Change in an Afromontane Centre of Endemism."</a> Ecography 36 (4): 518–530. </li>
    <li>Prisco, I., M. Carboni, et al. 2013. <a target="_blank" href="http://www.plosone.org/article/info%3Adoi%2F10.1371%2Fjournal.pone.0068850">"The fate of threatened coastal dune habitats in Italy under climate change scenarios."</a> PloS one 8(7).</li>
    <li>Prost, S., R. P. Guralnick, et al. 2013. <a target="_blank" href="http://www.ncbi.nlm.nih.gov/pubmed/23505210">"Losing ground: past history and future fate of Arctic small mammals in a changing climate."</a> Global Change Biology 19(6): 1854-1864.</li>
    <li>Rahn, E., P. Läderach, et al. 2013. <a target="_blank" href="http://dx.doi.org/10.1007/s11027-013-9467-x">"Climate change adaptation, mitigation and livelihood benefits in coffee production: where are the synergies?"</a> Mitigation and Adaptation Strategies for Global Change: 1-19.</li>
    <li>Ramirez-Villegas, J., A. J. Challinor, et al. 2013. <a target="_blank" href="http://stacks.iop.org/1748-9326/8/i=2/a=024018">"Implications of regional improvement in global climate models for agricultural impact research."</a> Environmental Research Letters 8(2): 024018.</li>
    <li>Razgour O, Juste J, Ibáñez C, Kiefer A, Rebelo H, Puechmaille SJ, Arlettaz R, Burke T, Dawson DA, Beaumont M, Jones G. 2013.  <a target="_blank" href="http://dx.doi.org/10.1111/ele.12158">"The Shaping of Genetic Variation in Edge-of-Range Populations Under Past and Future Climate Change."</a> Ecology Letters 16 (10): 1258–1266.</li>
    <li>Remesan, R., T. Bellerby, et al. 2013. <a target="_blank" href="http://doi.wiley.com/10.1002/hyp.9872">"Hydrological modelling using data from monthly GCMs in a regional catchment."</a> Hydrological Processes: n/a-n/a.</li>
    <li>Robinet C, Rousselet J, Roques A. 2013.  <a target="_blank" href="http://dx.doi.org/10.1007/s13595-013-0287-7">"Potential Spread of the Pine Processionary Moth in France: Preliminary Results from a Simulation Model and Future Challenges."</a> Annals of Forest Science: 1–12.</li>
    <li>Rodríguez-Pérez, J. R. and J. E. Beltrán-Vargas 2013. <a target="_blank" href="http://revistas.udistrital.edu.co/ojs/index.php/revcie/article/view/5073">"Análisis de escenarios de cambio climático A1B, A2 y B1 para la reserva forestal protectora bosque oriental de Bogotá años 2040, 2070 y 2095 utilizando MarksimGCM."</a> Revista Científica: 167-185.</li>
    <li>Sánchez-Fernández, D., P. Abellán, et al. 2013. <a target="_blank" href="http://dx.doi.org/10.1111/ddi.12104">"Do protected areas represent species' optimal climatic conditions? A test using Iberian water beetles."</a> Diversity and Distributions 19(11): 1407-1417.</li>
    <li>Sangmanee, C. G. W. and S. Pramot 2013. <a target="_blank" href="http://www.mijst.mju.ac.th/vol7/special1.html">"Simulating changes in discharge and suspended sediment loads of the Bangpakong River, Thailand, driven by future climate change."</a> Maejo Int. J. Sci. Technol.(7): 72-84.</li>
    <li>Singh, Piara, S Nedumaran, B R Ntare, K J Boote, N P Singh, K Srinivas, and M C S Bantilan. 2013.  <a target="_blank" href="http://dx.doi.org/10.1007/s11027-012-9446-7">"Potential Benefits of Drought and Heat Tolerance in Groundnut for Adaptation to Climate Change in India and West Africa."</a> Mitigation and Adaptation Strategies for Global Change: 1–21. doi:10.1007/s11027-012-9446-7. </li>
    <li>Skøien, J. O., M. Schulz, et al. 2013. <a target="_blank" href="http://www.sciencedirect.com/science/article/pii/S1574954112001203">"A Model Web approach to modelling climate change in biomes of Important Bird Areas."</a> Ecological Informatics 14(0): 38-43.</li>
    <li>Tuanmu, M.-N., A. Vina, et al. 2013. <a target="_blank" href="http://www.nature.com/nclimate/journal/v3/n3/abs/nclimate1727.html#supplementary-information">"Climate-change impacts on understorey bamboo species and giant pandas in China/'s Qinling Mountains."</a> Nature Clim. Change 3(3): 249-253.</li>
    <li>Van Soesbergen, A. J. J. and M. Mulligan 2013. <a target="_blank" href="http://www.earth-syst-dynam-discuss.net/4/567/2013/">"Modelling multiple threats to water security in the Peruvian Amazon using the WaterWorld Policy Support System."</a> Earth Syst. Dynam. Discuss. 4(1): 567-594.</li>
    <li>Watson, J. E. M., T. Iwamura, et al. 2013. <a target="_blank" href="http://dx.doi.org/10.1038/nclimate2007">"Mapping vulnerability and conservation adaptation strategies under climate change."</a> Nature Clim. Change 3(11): 989-994.</li>
    <li>Winzeler, H. E., P. R. Owens, et al. 2013. <a target="_blank" href="https://dl.sciencesocieties.org/publications/sssaj/abstracts/77/1/213">"A Methodology for Examining Changes in Soil Climate Geography through Time: U.S. Soil Moisture Regimes for the Period 1971–2000."</a> Soil Science Society of America Journal 77(1): 213-213.</li>
    <li>Xu, Zhonglin, Zhaodong Feng, Jianjun Yang, Jianghua Zheng, and Fang Zhang. 2013.  <a target="_blank" href="http://dx.doi.org/10.1371/journal.pone.0070728">" Nowhere to invade: Rumex cripus and Typha latifolia projected to disappear under future climate scenarios."</a> PLoS ONE 8 (7) (July 29): e70728.</li>
    <li>Yu, D., M. Chen, et al. 2013. <a target="_blank" href="http://dx.doi.org/10.1007/s10750-012-1213-y">"Global climate change will severely decrease potential distribution of the East Asian coldwater fish Rhynchocypris oxycephalus (Actinopterygii, Cyprinidae)."</a> Hydrobiologia 700(1): 23-32.</li>
  </ol>      

  <h5>2012</h5>
  <ol>
    <li>Beck, J. (2012). <a target="_blank" href="http://link.springer.com/article/10.1007%2Fs10584-012-0481-x?LI=true">"Predicting climate change effects on agriculture from ecological niche modeling: who profits, who loses?"</a>  Climatic Change, 1-13</li> 
    <li>Butler, C. J., et al. (2012). <a target="_blank" href="http://www.bioone.org/doi/abs/10.3159/TORREY-D-11-00049.1">"Distribution of the threatened lace hedgehog cactus (Echinocereus reichenbachii) under various climate change scenarios."</a> The Journal of the Torrey Botanical Society 139(1): 46-55.</li>
    <li>Bütof, A. et al., 2012. <a target="_blank" href="http://onlinelibrary.wiley.com/doi/10.1111/j.1365-2486.2011.02539.x/full">The responses of grassland plants to experimentally simulated climate change depend on land use and region</a>. Global Change Biology, 18(1): 127-137.</li>
    <li>Chung, U., et al. (2011). <a target="_blank" href="http://www.plosone.org/article/info%3Adoi%2F10.1371%2Fjournal.pone.0027439">"Predicting the Timing of Cherry Blossoms in Washington, DC and Mid-Atlantic States in Response to Climate Change."</a> PLoS ONE 6(11): e27439.</li>
    <li>Congli, D., G. Schoups, et al. 2012. <a target="_blank" href="http://web.a.ebscohost.com/abstract?direct=true&profile=ehost&scope=site&authtype=crawler&jrnl=15829596&AN=91924710&h=6uX/deUqR3oXLEWkhdYKYdb3jBEkaxsXkqTjN4b0NuP9PNeJHQTiqyvKppRIYaaoMQIpHnDSkbNSbh8XsA8GEg==&crl=c">"Probabilistic Scenario Development to estimate Future Runoff in the yellow River Basin, China."</a> Environmental Engineering & Management Journal (EEMJ) Vol. 12(Issue 7): p1457-1463. 1457p.</li>
    <li>Cossani, C. M. and M. P. Reynolds 2012. <a target="_blank" href="http://www.plantphysiol.org/content/160/4/1710">"Physiological traits for improving heat tolerance in wheat."</a> Plant Physiol 160(4): 1710-1718.</li>
    <li>Cross, M. S., Schrag, A. M., Girvetz, E. H., & Enquist, C. A. (2012). <a target="_blank" href="http://www.springer.com/environment/global+change+-+climate+change/book/978-1-61091-203-7">"Landscape and Seascape Climate Change Planning and Action."</a> Climate and Conservation, 16-30.</li>
    <li>Daniele de Rigo. (2012). <a target="_blank" href="http://www.iemss.org/sites/iemss2012/proceedings/D3_1_0715_deRigo.pdf.">"Semantic Array Programming for Environmental Modelling: Application of the Mastrave Library"</a> Int. Environ. Model. Softw. Soc. 2012. </li>
    <li>Davis, A. P., T. W. Gole, et al. 2012. <a target="_blank" href="http://dx.plos.org/10.1371/journal.pone.0047981">"The impact of climate change on indigenous Arabica coffee (Coffea arabica): predicting future trends and identifying priorities."</a> PloS one 7(11): e47981-e47981.</li>
    <li>Diamond, S. E., L. M. Nichols, et al. 2012. <a target="_blank" href="http://dx.doi.org/10.1890/11-2296.1">"A physiological trait-based approach to predicting the responses of species to experimental climate warming."</a> Ecology 93(11): 2305-2312.</li>
    <li>Diamond, S.E. et al., 2012. <a target="_blank" href="http://people.umass.edu/ideltoro/index_files/ThermalTolerance1.pdf">A global analysis of the climatic, ecological, and evolutionary determinants of warming tolerance in ants</a>. Global Change Biology, 18(2): 448-456.</li>
    <li>Dimitrov, D., D. Nogués-Bravo, et al. 2012. <a target="_blank" href="http://dx.plos.org/10.1371/journal.pone.0048908">"Why do tropical mountains support exceptionally high biodiversity? The Eastern Arc mountains and the drivers of Saintpaulia diversity."</a> PloS one 7(11): e48908-e48908.</li>
    <li>Domisch, S., et al. (2012). <a target="_blank" href="http://onlinelibrary.wiley.com/doi/10.1111/gcb.12107/abstract">"Modelling distribution in European stream macroinvertebrates under future climates."</a> Global Change Biology: n/a-n/a.</li>
    <li>Eitzinger, A., P. Läderach, et al. 2012. <a target="_blank" href="http://link.springer.com/10.1007/s11027-012-9432-0">"Implications of a changing climate on food security and smallholders’ livelihoods in Bogotá, Colombia."</a> Mitigation and Adaptation Strategies for Global Change 19(2): 161-176.</li>
    <li>Estrada-Peña, A., Sánchez, N., & Estrada-Sánchez, A. (2012). <a target="_blank" href="http://www.ncbi.nlm.nih.gov/pubmed/22448680">"An assessment of the distribution and spread of the tick Hyalomma marginatum in the western Palearctic under different climate scenarios."</a> Vector-Borne and Zoonotic Diseases.</li>
    <li>Feeley, K. J., & Rehm, E. M. (2012). <a target="_blank" href="http://onlinelibrary.wiley.com/doi/10.1111/gcb.12012/abstract">"Amazon's vulnerability to climate change heightened by deforestation and man-made dispersal barriers."</a> Global Change Biology.</li>
    <li>Forrest, J. L., E. Wikramanayake, et al. 2012. <a target="_blank" href="http://www.sciencedirect.com/science/article/pii/S0006320712001437">"Conservation and climate change: Assessing the vulnerability of snow leopard habitat to treeline shift in the Himalaya."</a> Biological Conservation 150(1): 129-135.</li>
    <li>Gallagher, R. V., Englert Duursma, D., O’Donnell, J., Wilson, P. D., Downey, P. O., Hughes, L., & Leishman, M. R. (2012). <a target="_blank" href="http://link.springer.com/article/10.1007/s10530-012-0342-6">"The grass may not always be greener: projected reductions in climatic suitability for exotic grasses under future climates in Australia."</a> Biological Invasions, 1-15.</li>
    <li>García-López, J. M., & Allué, C. (2012). <a target="_blank" href="http://www.sciencedirect.com/science/article/pii/S0921818112002299">"Modelling future no-analogue climate distributions: A world-wide phytoclimatic niche-based survey."</a> Global and Planetary Change.</li>
    <li>Giannini, T. C., A. L. Acosta, et al. 2012. <a target="_blank" href="http://dx.doi.org/10.1016/j.ecolmodel.2012.06.035">"Pollination services at risk: Bee habitats will decrease owing to climate change in Brazil."</a> Ecological Modelling 244(0): 127-131.</li>
    <li>Hof AR, Jansson R, Nilsson C. 2012.  <a target="_blank" href="http://dx.doi.org/10.1111/j.1472-4642.2011.00876.x ">"How Biotic Interactions May Alter Future Predictions of Species Distributions: Future Threats to the Persistence of the Arctic Fox in Fennoscandia."</a> Diversity and Distributions 18 (6): 554–562. </li>
    <li>Hof, A. R., R. Jansson, et al. 2012. <a target="_blank" href="http://www.plosone.org/article/info%3Adoi%2F10.1371%2Fjournal.pone.0052574">"Future climate change will favour non specialist mammals in the (Sub)arctics."</a> PLoS ONE 7(12): e52574.</li>
    <li>Hof, A. R., R. Jansson, et al. 2012. <a target="_blank" href="http://onlinelibrary.wiley.com/doi/10.1111/j.1472-4642.2011.00876.x/abstract">"How biotic interactions may alter future predictions of species distributions: future threats to the persistence of the arctic fox in Fennoscandia."</a> Diversity and Distributions, 18: 554-562.</li>
    <li>Hof, A. R., R. Jansson, et al. 2012. <a target="_blank" href="http://www.sciencedirect.com/science/article/pii/S0304380012003778">"The usefulness of elevation as a predictor variable in species distribution modelling."</a> Ecological Modelling: 246: 286-290.</li>
    <li>Huang, P., & Schaal, B. A. (2012). <a target="_blank" href="http://www.ncbi.nlm.nih.gov/pubmed/23125436">"Association between the geographic distribution during the last glacial maximum of Asian wild rice, Oryza rufipogon (Poaceae), and its current genetic variation."</a> American journal of botany, 99(11), 1866-1874.</li>
    <li>Hughes, A. C., et al. (2012). <a target="_blank" href="http://onlinelibrary.wiley.com/doi/10.1111/j.1365-2486.2012.02641.x/abstract">"The projected effects of climatic and vegetation changes on the distribution and diversity of Southeast Asian bats."</a> Global Change Biology 18(6): 1854-1865.</li>
    <li>Ihlow, F. et al., 2012. <a target="_blank" href="http://onlinelibrary.wiley.com/doi/10.1111/j.1365-2486.2011.02623.x/full">On the brink of extinction? How climate change may affect global chelonian species richness and distribution</a>. Global Change Biology. DOI: 10.1111/j.1365-2486.2011.02623.x.</li>
    <li>Jarvis, A., Ramirez-Villegas, J., Herrera Campo, B. and Navarro-Racines, C., 2012. <a target="_blank" href="http://www.springerlink.com/content/n36675226277455j">Is Cassava the Answer to African Climate Change Adaptation?</a> Tropical Plant Biology: 1-21.</li>
    <li>Jones, G. V. and F. Alves 2012. <a target="_blank" href="http://dx.doi.org/10.1504/IJGW.2012.049448">"Impact of climate change on wine production: a global overview and regional assessment in the Douro Valley of Portugal."</a> International Journal of Global Warming 4(3): 383-406.</li>
    <li>Kapeller, S., M. J. Lexer, et al. 2012. <a target="_blank" href="http://www.sciencedirect.com/science/article/pii/S0378112712000631">"Intraspecific variation in climate response of Norway spruce in the eastern Alpine range: Selecting appropriate provenances for future climate."</a> Forest Ecology and Management 271: 46-57.</li>
    <li>Keller, S. R., Levsen, N., Olson, M. S., & Tiffin, P. (2012). <a target="_blank" href="http://www.ncbi.nlm.nih.gov/pubmed/22513286">"Local Adaptation in the Flowering-Time Gene Network of Balsam Poplar, Populus balsamifera L."</a> Molecular Biology and Evolution, 29(10), 3143-3152.</li>
    <li>Lee, D. N., M. Papeş, et al. 2012. <a target="_blank" href="http://dx.plos.org/10.1371/journal.pone.0042466">"Present and potential future distribution of common vampire bats in the Americas and the associated risk to cattle."</a> PloS one 7(8): e42466-e42466.</li>
    <li>Loiseau, C., et al. (2012). <a target="_blank" href="http://www.plosone.org/article/info%3Adoi%2F10.1371%2Fjournal.pone.0044729">"First Evidence and Predictions of <italic>Plasmodium</italic> Transmission in Alaskan Bird Populations."</a> PLoS ONE 7(9): e44729.</li>
    <li>Loyola, R. D., Lemes, P., Faleiro, F. V., Trindade-Filho, J., & Machado, R. B. (2012). <a target="_blank" href="http://www.plosone.org/article/info:doi/10.1371/journal.pone.0046257">"Severe loss of suitable climatic conditions for marsupial species in Brazil: challenges and opportunities for conservation."</a> PloS one, 7(9), e46257</li>
    <li>Luedeling, E., & Neufeldt, H. (2012). <a target="_blank" href="http://link.springer.com/article/10.1007%2Fs10584-012-0438-0">"Carbon sequestration potential of parkland agroforestry in the Sahel."</a> Climatic Change, 1-19.</li>
    <li>Luna-Vega, I., O. Alcántara-Ayala, et al. 2012. <a target="_blank" href="http://www.nrcresearchpress.com/doi/abs/10.1139/b2012-019#.UvULWvl5M1I">"Ecological niche modeling on the effect of climatic change and conservation of Ternstroemia lineata DC. (Ternstroemiaceae) in Mesoamerica."</a> Botany 90(7): 637-650.</li>
    <li>Markovic, D., Freyhof, J., & Wolter, C. (2012). <a target="_blank" href="http://www.plosone.org/article/info%3Adoi%2F10.1371%2Fjournal.pone.0040530">"Where Are All the Fish: Potential of Biogeographical Maps to Project Current and Future Distribution Patterns of Freshwater Species."</a> PloS one, 7(7), e40530.</li>
    <li>Mbatudde, M., Mwanjololo, M., Kakudidi, E. K., & Dalitz, H. (2012). <a target="_blank" href="http://onlinelibrary.wiley.com/doi/10.1111/j.1365-2028.2012.01327.x/abstract">"Modelling the potential distribution of endangered Prunus africana (Hook. f.) Kalkm. in East Africa."</a> African Journal of Ecology.</li>
    <li>Nadav Nur, Leonardo Salas, Samuel Veloz, Julian Wood, Leonard Liu, and Grant Ballard . (2012). <a target="_blank" href="http://climate.calcommons.org/sites/default/files/LCC%20PRBO%20SFBay%20TidalMarsh%20Demogr%20ClimateChange_2012.pdf">"Assessing Vulnerability of Tidal Marsh Birds to Climate Change through the Analysis of Population Dynamics and Viability. Technical Report."</a> Report to the California Landscape Conservation Cooperative. Version 1.0</li>
    <li>Nyabako, T. and E. Manzungu (2012). <a target="_blank" href="http://www.ccsenet.org/journal/index.php/enrr/article/view/15244/10593">"An Assessment of the Adaptability to Climate Change of Commercially Available Maize Varieties in Zimbabwe."</a> Environment and Natural Resources Research 2(1).</li>
    <li>Pfenninger, M., Bálint, M., & Pauls, S. U. (2012). <a target="_blank" href="http://www.biomedcentral.com/1471-2148/12/224">"Methodological framework for projecting the potential loss of intraspecific genetic diversity due to global climate change."</a> BMC evolutionary biology, 12(1), 224.</li>
    <li>Platts, P. J., et al. (2012). <a target="_blank" href="http://onlinelibrary.wiley.com/doi/10.1111/j.1600-0587.2012.07805.x/abstract">"Spatial heterogeneity of climate change in an Afromontane centre of endemism."</a> Ecography.</li>
    <li>Rahimi, J., M. Ebrahimpour, et al. 2012. <a target="_blank" href="http://link.springer.com/10.1007/s00704-012-0741-8">"Spatial changes of Extended De Martonne climatic zones affected by climate change in Iran."</a> Theoretical and Applied Climatology 112(3-4): 409-418.</li>
    <li>Ramirez-Villegas, J. and A. Challinor 2012. <a target="_blank" href="http://www.sciencedirect.com/science/article/pii/S0168192312001244">"Assessing relevant climate data for agricultural applications."</a> Agricultural and Forest Meteorology 161: 26-45.</li>
    <li>Rocha, J., A. Crespí, et al. 2012. <a target="_blank" href="http://dx.doi.org/10.1080/17550874.2012.671857">"Status and conservation of Silene section Cordifolia in the Iberian Peninsula: a menaced group under global environmental change."</a> Plant Ecology & Diversity 5(1): 45-56.</li>
    <li>Rodríguez-Castañeda G, Hof AR, Jansson R, Harding LE. 2012.  <a target="_blank" href="http://dx.doi.org/10.1371/journal.pone.0044402">"Predicting the Fate of Biodiversity Using Species’ Distribution Models: Enhancing Model Comparability and Repeatability."</a> PLoS ONE 7 (9) (September 11): e44402. </li>
    <li>Rodríguez-Castañeda, G., A. R. Hof, et al. 2012. <a target="_blank" href="http://europepmc.org/abstract/MED/22984502">"Predicting the fate of biodiversity using species' distribution models: enhancing model comparability and repeatability."</a> PloS one 7(9): e44402.</li>
    <li>Romo, H., Sanabria, P., & García-Barros, E. (2012) <a target="_blank" href="http://www.uam.es/personal_pdi/ciencias/egb/download/Romo_et_al_2012_Prediccion_impactos_Boloria.pdf">"Predicción de los impactos del cambio climático en la distribución de lepidópteros del género Boloria Moore, 1900 en la Península Ibérica (Lepidoptera: Nymphalidae)."</a> </li>
    <li>Shah, Ram Devi Tachamo, Deep Narayan Shah, and Sami Domisch. 2012.  <a target="_blank" href="http://dx.doi.org/10.1080/13887890.2012.697399">"Range Shifts of a Relict Himalayan Dragonfly in the Hindu Kush Himalayan Region Under Climate Change Scenarios."</a> International Journal of Odonatology 15 (3) (July 10): 209–222. </li>
    <li>Singh, P., et al. (2012). <a target="_blank" href="http://onlinelibrary.wiley.com/doi/10.1111/j.1439-037X.2012.00522.x/abstract">"Evaluation of Genetic Traits for Improving Productivity and Adaptation of Groundnut to Climate Change in India."</a> Journal of Agronomy and Crop Science 198(5): 399-413.</li>
    <li>Sonder, K., C. C. Okonkwo, et al. 2010. <a target="_blank" href="http://repository.cimmyt.org/xmlui/handle/10883/3324?show=full">"Predicted changes in suitability and agro climatic factors due to climate change for yam production in Nigeria."</a> African Journal of Root and Tuber Crops 8(2): 51-59.</li>
    <li>Song, L., W.-Y. Liu, et al. 2012. <a target="_blank" href="http://dx.doi.org/10.1016/j.biocon.2012.04.002">"Response of non-vascular epiphytes to simulated climate change in a montane moist evergreen broad-leaved forest in southwest China."</a> Biological Conservation 152(0): 127-135.</li>
    <li>Thomas, E., et al. (2012). <a target="_blank" href="http://www.plosone.org/article/info%3Adoi%2F10.1371%2Fjournal.pone.0047676">"Present Spatial Diversity Patterns of Theobroma cacao L. in the Neotropics Reflect Genetic Differentiation in Pleistocene Refugia Followed by Human-Influenced Dispersal."</a> PLoS ONE 7(10): e47676. </li>
    <li>Velásquez-Tibatá, J., P. Salaman, et al. 2012. <a target="_blank" href="http://link.springer.com/10.1007/s10113-012-0329-y">"Effects of climate change on species distribution, community structure, and conservation of birds in protected areas in Colombia."</a> Regional Environmental Change 13(2): 235-248.</li>
  </ol>

  <h5>2011</h5>
  <ol>
    <li>Dempe, H., Bittner, T., Jaeschke, A., & Beierkuhnlein, C. (2011). <a target="_blank" href="environmental envelope modelling to nature conservation strategies.">"Habitat coherence and climate change: an analysis application for the Natura 2000 network in Germany. Climate change impacts on habitats and biodiversity"</a> environmental envelope modelling to nature conservation strategies.</li>
    <li>Heubes, J. et al., 2011. <a target="_blank" href="http://onlinelibrary.wiley.com/doi/10.1111/j.1365-2699.2011.02560.x/full">Modelling biome shifts and tree cover change for 2050 in West Africa</a>. Journal of Biogeography, 38(12): 2248-2258.</li>
    <li>Hof AR. 2011. <a target="_blank" href=" ">" European terrestrial gastropod distribution. How may climate change affect their diversity and current distribution. In: Bianchi, A. and Fields, J. (eds), Gastropods: Diversity, Habitat and Genetics."</a> Nova Science Publishers, Inc., Hauppauge, New York pp. 165-182</li>
    <li>Jarvis, A., Lane, A. and Hijmans, R.J., 2008. <a target="_blank" href="http://www.sciencedirect.com/science/article/pii/S0167880908000133">The effect of climate change on crop wild relatives</a>. Agriculture, Ecosystems &amp; Environment, 126(1-2): 13-23.</li>
    <li>Jenkins, C.N. et al., 2011. <a target="_blank" href="http://onlinelibrary.wiley.com/doi/10.1111/j.1472-4642.2011.00770.x/abstract">Global diversity in light of climate change: the case of ants</a>. Diversity and Distributions, 17(4): 652-662.</li>
    <li>Laderach, P., M. Lundy, et al. 2011. <a target="_blank" href="http://link.springer.com/chapter/10.1007%2F978-3-642-14776-0_42">"Predicted Impact of Climate Change on Coffee Supply Chains. The Economic, Social and Political Elements of Climate Change."</a> W. Leal Filho, Springer Berlin Heidelberg: 703-723.</li>
    <li>Loiselle, B.A., Graham, C.H., Goerck, J.M. and Ribeiro, M.C., 2010. <a target="_blank" href="http://onlinelibrary.wiley.com/doi/10.1111/j.1365-2699.2010.02285.x/full">Assessing the impact of deforestation and climate change on the range size and environmental niche of bird species in the Atlantic forests, Brazil</a>. Journal of Biogeography, 37(7): 1288-1301.</li>
    <li>Mulligan, M. et al., 2010. <a target="_blank" href="http://www.infoandina.org/sites/default/files/recursos/the_andes_basins.pdf">The Andes basins: biophysical and developmental diversity in a climate of change</a>. Water International, 35(5): 472-492.</li>
    <li>Mulligan, M. et al., 2011. <a target="_blank" href="www.tandfonline.com/doi/abs/10.1080/02508060.2011.543408">The nature and impact of climate change in the Challenge Program on Water and Food (CPWF) basins</a>. Water International, 36(1): 96-124.</li>
    <li>Ramirez-Villegas, J., Jarvis, A. and Läderach, P., 2011. <a target="_blank" href="http://www.sciencedirect.com/science/article/pii/S0168192311002814">Empirical approaches for assessing impacts of climate change on agriculture: The EcoCrop model and a case study with grain sorghum</a>. Agricultural and Forest Meteorology: 1-12.</li>
    <li>Rödder, D. and Schulte, U., 2010. <a target="_blank" href="http://www.springerlink.com/content/7575225168472135">Potential loss of genetic variability despite well established network of reserves: the case of the Iberian endemic lizard <i>Lacerta schreiberi</i></a>. Biodiversity and Conservation, 19(9): 2651-2666.</li>
    <li>Rödder, D., Bohme, W., and Lotters, S., 2011. <a target="_blank" href="http://www.salamandra-journal.com/index.php?option=com_docman&amp;task=doc_download&amp;gid=233&amp;Itemid=72">'Chamaliens' on the Hawaiian Islands: spatial risk assessment for the invasive Jackson's chameleon (Chamaeleonidae)</a>. Salamandra 47(1): 36-42. ISSN 0036-3375.</li>
    <li>Stensgaard, A.S. et al., 2011. <a target="_blank" href="http://www.sciencedirect.com/science/article/pii/S0001706X11003366">Large-scale determinants of intestinal schistosomiasis and intermediate host snail distribution across Africa: Does climate matter?</a> Acta Tropica.</li>
  </ol>

  <h5>&lt; 2010</h5>
  <ol>
    <li> Giraldo, D., Juarez, H., Pérez, W., Trebejo, I., Yzarra, W. & Forbes G. (2010) <a target="_blank" href="Severidad del tizón tardío de la papa (Phytophthora infestans) en zonas agrícolas del Perú asociado con el cambio climático.">"Severidad del tizón tardío de la papa (Phytophthora infestans) en zonas agrícolas del Perú asociado con el cambio climático."</a> Revista Peruana Geo-Atmosférica Rpga (2), 56-67. </li>
    <li> Loiselle, B.A., Graham, C.H., Goerck, J.M. and Ribeiro, M.C., 2010. <a target="_blank" href="http://onlinelibrary.wiley.com/doi/10.1111/j.1365-2699.2010.02285.x/full">"Assessing the impact of deforestation and climate change on the range size and environmental niche of bird species in the Atlantic forests, Brazil."</a> Journal of Biogeography, 37(7): 1288-1301.</li>
    <li> Mulligan, M. et al., 2010. <a target="_blank" href="http://www.infoandina.org/sites/default/files/recursos/the_andes_basins.pdf">"The Andes basins: biophysical and developmental diversity in a climate of change."</a> Water International, 35(5): 472-492.</li>
    <li> Rödder, D. and Schulte, U., 2010.  <a target="_blank" href="http://www.springerlink.com/content/7575225168472135">"Potential loss of genetic variability despite well established network of reserves: the case of the Iberian endemic lizard Lacerta schreiberi."</a> Biodiversity and Conservation, 19(9): 2651-2666.</li>
  </ol>

  <h5>Book chapters</h5>
  <ol>
	<li> Babel, MS, A Agarwal, and VR Shinde. 2014. <a target="_blank" href="https://books.google.com.co/books?hl=en&lr=&id=UMuSAwAAQBAJ&oi=fnd&pg=PA109&dq=“Downscaling+global+circulation+model+outputs:+the+delta+method+decision+and+policy+analysis”&ots=MKcywqWn-T&sig=a9BNzHDb-580_XGU_eSvm8-sO_A">"Climate Change Impacts on Water Resources and Selected Water Use Sectors."</a> Climate Change and Water Resources.</li>
	<li> Beebe, S. et al., 2011. <a target="_blank" href="http://onlinelibrary.wiley.com/doi/10.1002/9780470960929.ch25/summary">"Chapter 16: Genetic Improvement of Common Beans and the Challenges of Climate Change. Crop Adaptation to Climate Change. "</a> Wiley & Sons.</li>
	<li> Carne, C., Semple, S., Lehmann, J. 2012. <a target="_blank" href="http://ntrs.nasa.gov/archive/nasa/casi.ntrs.nasa.gov/20120013440_2012013015.pdf#page=327">"Chapter 14: "The Effects of Climate Change on Orangutans: A Time Budget Model."</a> Climate Models. InTech.</li>
	<li> Ceballos, H., Ramirez-Villegas, J., Bellotti, A.C., Jarvis, A. and Alvarez, E., 2011. <a target="_blank" href="http://www.wiley.com/WileyCDA/WileyTitle/productCd-0813820162.html">"Chapter 19: Adaptation of Cassava to Changing Climates. Crop Adaptation to Climate Change. "</a> Wiley & Sons.</li>
	<li> Center, I, and E Ababa. 2014. <a target="_blank" href="https://books.google.com.co/books?hl=en&lr=&id=FseWBAAAQBAJ&oi=fnd&pg=PA186&dq=“ccafs-climate.org”&ots=YCBvnIeWm_&sig=zoKWeQyhcIaf3Ge9R_lvozXooKU">"Shaping Sustainable Intensive Production Systems: Improved Crops and Cropping Systems in the Developing World."</a> Climate Change Impact and Adaptation in Agricultural Systems.</li>
	<li> Cross, M. S.; Schrag, A.M., Givertz, E.H.; Enquist, C.A. 2012. <a target="_blank" href="http://link.springer.com/chapter/10.5822/978-1-61091-203-7_2#page-1.">"Landscape and Seascape Cliamte CHange Planning and Action."</a> Climate and Conservation: Landscape and Seascape Science, Planning, and Action. Washington D.C., USA: Island Press.</li>
	<li> Druyan, L. M. 2012. <a target="_blank" href="http://pubs.giss.nasa.gov/abs/dr07300k.html">"Climate Models."</a> Croatia. InTech.</li>
	<li> Geismar J, Haase P, Nowak C. <a target="_blank" href="http://www.springer.com/life+sciences/entomology/book/978-94-017-9339-1.">"Modeling the Spatio-Temporal Dynamics of the Pine Procesionary Month."</a> In Processionary Moths and Climate Change : An Update, 427. Springer.</li>
	<li> Ghebru, B.; Woldcamlak, A.; Ogbazghi, W.; Gebreselassie, M.; Thomas, T. S. 2013. <a target="_blank" href="http://www.ifpri.org/sites/default/files/publications/rr181ch05.pdf.">"Eritrea."</a> East African Agriculture and Climate Change: A Comprehensive Analysis. Washington D.C., USA: Pinceton Editorial Associates Inc.</li>
	<li> Giannini, T. C., A. L. Acosta, et al. 2012. <a target="_blank" href="http://myrtus.uspnet.usp.br/statuspolin/17.html">"Impacto de mudanças climáticas em abelhas solitárias: um estudo de caso envolvendo duas espécies de Centris. Polinizadores no Brasil."</a> São Paulo, EDUSP: 335 - 348.</li>
	<li> Hof, A. R. 2011. <a target="_blank" href="http://umu.diva-portal.org/smash/record.jsf?pid=diva2:462007">"European terrestrial gastropod distribution. How may climate change affect their diversity and current distribution."</a> Nova Science Publishers, Inc.: 165-182.</li>
	<li> Jarvis, A., J. Ramírez-Villegas, et al. 2013. <a target="_blank" href="http://ciat.cgiar.org/wp-content/uploads/2012/12/chapter_3_eco_efficiency.pdf">"Are Climate Change Adaptation and Mitigation Options Eco-Efficient? Eco-Efficiency: From Vision to Reality. I. C. f. T. A."</a> (CIAT). Cali, Colombia.</li>
	<li> Jarvis, A., Ramirez-Villegas, J., Bonilla-Findji, O. and Zapata, E., 2011. <a target="_blank" href="http://www.wiley.com/WileyCDA/WileyTitle/productCd-0813820162.html">"Chapter 3.1: Impacts of Climate Change on Crop Production in Latin America. Crop Adaptation to Climate Change. "</a> Wiley & Sons.</li>
	<li> Porter, J. R.; Soussana, J. F.; Fereres, E., Long, S.; Mohren, F. ; Peltonen-Sainio, P.; Von Braun, J. 2013. <a target="_blank" href="https://books.google.com.co/books?hl=es&lr=&id=EmOes-iIaeAC&oi=fnd&pg=PR5&dq=Handbook+of+Climate+Change+and+Agroecosystems:+Global+and+Regional+Aspects+and+Implications&ots=AQzM1jriHe&sig=uBrykDaQcWn4A1cqkp_hAzC_4GA#v=onepage&q=Handbook of Climate Change.">"European Perspectives: An Agronomic Science Plan for Food Security in a Changing Climate."</a> Handbook of Climate Change and Agroecosystems: Global and Regional Aspects and Implications. Imperial College Press.</li>
	<li> Ramirez-Villegas, J., A. Jarvis, et al. 2013. <a target="_blank" href="http://www.publish.csiro.au/pid/7037.htm">"Crop and forage genetic resources: international interdependence in the face of climate change. Crop genetic resources as a global commons: challenges in international law and governance."</a> p78-98.</li>
	<li> Ramirez-Villegas, J., Jarvis, A., Van den Bergh, I., Staver, C. and Turner, D., 2011. <a target="_blank" href="http://www.wiley.com/WileyCDA/WileyTitle/productCd-0813820162.html">"Chapter 20: Changing Climates: Effects on Growing Conditions for Banana and Plantain (Musa spp.) and Possible Responses. Crop Adaptation to Climate Change."</a> Wiley & Sons.</li>
	<li> Ribeiro, M. C., Camargo Martensen, A., Metzger, J.P., Tabarelli, M., Scarano, F., and Fortin, M.J., 2011. <a target="_blank" href="http://www.springer.com/life+sciences/ecology/book/978-3-642-20991-8">"Chapter 21: The Brazilian Atlantic Forest: A Shrinking Biodiversity Hostpot. Biodiversity Hotspots. Springer Verlag, "</a> ISBN 978-3-642-20991-8.</li>
	<li> Roques, L.; Rossi, J. P.; Berestycki, H., Rousselet, J., Garnier, J.; Roquejoffre, J. M.; Rossi, L.; Soubeyrand, S.; Robinet, C. 2015. <a target="_blank" href="http://www.springer.com/life+sciences/entomology/book/978-94-017-9339-1.">"Modeling the Spatio-Temporal Dynamics of the Pine Procesionary Month."</a> Processionary Moths and Climate Change : An Update. Springer.</li>
	<li> Schafleitner, R. et al., 2011. <a target="_blank" href="http://www.wiley.com/WileyCDA/WileyTitle/productCd-0813820162.html">"Chapter 11: Adaptation of the Potato Crop to Changing Climates. Crop Adaptation to Climate Change. "</a> Wiley & Sons.</li>
	<li> Sterling, E.; Bynum, N.; Blair, M. 2013.  <a target="_blank" href="http://www.oxfordscholarship.com/view/10.1093/acprof:oso/9780199659449.001.0001/acprof-9780199659449.">"Primate Ecology and Conservation: A Handbook of Techniques. "</a> Oxford, UK: Oxford University Press.</li>
	<li> Stirling, C.; Hellin, J.; Cairns, J.; Silverblatt-Buser, E.; Tefera, T.; Ngugi, H.; Gbegbelegbe, S.; Tesfaye, K.; Chung, U.; Sonder, K.; Cox, R. A.; Verhulst, N.; Govaerts, B.; Alderman, P.; Reynolds, M. 2014. <a target="_blank" href="http://www.cabi.org/cabebooks/ebook/20143234512.">"Shaping Sustainable Intensive Production Systems: Improved Crops and Cropping Systems in the Developing World."</a> Climate Change Impact and Adaptation in Agricultural Systems. CAB International. doi:10.1079/9781780642895.0000.</li>
	<li> Trabucco, A, R Zomer, PK Thornton, and J Koo. 2014.  <a target="_blank" href="https://books.google.com.co/books?hl=en&lr=&id=vIqtBAAAQBAJ&oi=fnd&dq=“ccafs-climate.org”&ots=ZorZ-eTTF4&sig=WlfL61edKsGo96UP1-csZfRG6i4">"Drivers of Change."</a> </li>
	<li> Van Zonneveld, M.;, and J. I. Dawson, I.; Thomas, E.; \cheldeman, X.; Van Etten, J.; Loo, J.; Hormaza. 2014. <a target="_blank" href="http://www.researchgate.net/publication/258628094_Genomics_of_Plant_Genetic_Resources_2014_pp_67-91_Application_of_Molecular_Markers_in_Spatial_Analysis_to_Optimize_In_Situ_Conservation_of_Plant_Genetic_Resources">"Application of Molecular Markers in Spatial Analysis to Optimize In Situ Conservation of Plant Genetic."</a> Genomics of Plant Genetic Resources, 67–91. Springer.</li>
	<li> Winkler, J.A.; Andresen, J.A; Hatfield, J.L.; Bidwell, D. & Brow, D. 2014. <a target="_blank" href="https://books.google.com.co/books?hl=en&lr=&id=QRUQBAAAQBAJ&oi=fnd&pg=PR2&dq=%22ccafs-climate.org%22&ots=f44xi0IBip&sig=El6ZpLwBt6lTogz2gZbI1p7YVWU">"Climate Projections for the Midwest Availability, Interpretation and Synthesis."</a> Climate Change in the Midwest: A Synthesis Report for the National Climate Assessment. Washington D.C., USA: Island Press.</li>
  </ol>

  <h5>Theses and reports</h5>
  <ol>
	<li> ADB 2009. <a target="_blank" href="http://www.ifad.org/drd/agriculture/132.htm">"Climate Change, Food Security, and Sound Economic Livelihood in Pacific Island Countries."</a> Mandaluyong City, Philippines, Asian Development Bank.</li>
	<li> Aguilar, R. 2012. <a target="_blank" href="http://www.pieb.com.bo/agua_preeva.php?id=2">"Evaluación de la vulnerabilidad, amenazas y riesgos asociados al cambio climático para la planificación del desarrollo en el municipio de Yunchará."</a> Yunchará, Bolivia, PROMETA.</li>
	<li> Anayah, F. M. A. 2012. <a target="_blank" href="http://digitalcommons.usu.edu/etd/1306/">"Improving Complementary Methods To PredictEvapotranspiration For Data Deficit Conditionsand Global Applications Under Climate Change."</a> All Graduate Theses and Dissertations. Utah, Utah State University. PhD Civil and Environmental Engineering.</li>
	<li> Argote, K, A Jarvis, A Nowak, and M Lizarazo. 2014. <a target="_blank" href="https://cgspace.cgiar.org/handle/10568/51367">"Climate-Smart Agriculture in Colombia. Washington D.C., USA."</a> </li>
	<li> Baca, M, A Nowak, M Lizarazo, and P Imbach. 2014. <a target="_blank" href="https://cgspace.cgiar.org/handle/10568/49672">"Climate-Smart Agriculture in Peru. Washington D.C., USA."</a> </li>
	<li> Benedikter, A., P. Läderach, et al. 2012. <a target="_blank" href="http://ciat.cgiar.org/wp-content/uploads/2013/09/politicas_sintesis11_cambio_climatico_mundial_cadenas_suministro.pdf">"Cambio climático mundial y cadenas de suministro de alimentos: Políticas para la adaptación colectiva. CIAT Políticas en Síntesis No. 11."</a> Centro Internacional de Agricultura Tropical. (CIAT). Cali, Colombia: 8 p.</li>
	<li> Byrne, TR. 2014. <a target="_blank" href="https://www.uleth.ca/dspace/handle/10133/3500">"Household Adaptive Capacity and Current Vulnerability to Future Climate Change in Rural Nicaragua."</a> University of Lethbridg.</li>
	<li> Caffrey, P. e. a. 2013. <a target="_blank" href="http://community.eldis.org/.5bb2fb84">"Uganda Climate Change Vulnerability Assessment Report."</a> Uganda: 76-76.</li>
	<li> Caley, P., Tennant, P., and Hood, G., 2011. <a target="_blank" href="http://www.feral.org.au/wp-content/uploads/2011/06/ClimateChangeRept.pdf">"Modelling the distribution of vertebrate pests in New South Wales under climate change. Invasive Animals Cooperative Research Centre. "</a> University of Canberra, ACT 2600, May 2011. ISBN: 978-1-921777-08-0.</li>
	<li> Centro Internacional de Agricultura Tropical. 2013. <a target="_blank" href="http://ciat.cgiar.org/wp-content/uploads/2013/09/politicas_sintesis11_cambio_climatico_mundial_cadenas_suministro.pdf">"Evaluación de la vulnerabilidad al cambio climático de la agricultura en la región Andina de Colombia. CIAT Políticas en Síntesis No. 13."</a> Centro Internacional de Agricultura Tropical. (CIAT). Cali, Colombia: 6 p.</li>
	<li> CIAT 2013. <a target="_blank" href="http://dapa.ciat.cgiar.org/wp-content/uploads/big-files/2013/Resumen_Final_v5_new.pdf">"Evaluación de la vulnerabilidad al cambio climático de la agricultura y del recurso hídrico en los Andes de Colombia, Ecuador y Perú."</a> Cali, Colombia, Área de Investigación en Análisis de Políticas (DAPA) - Centro Internacional de AgriculturaTropical (CIAT)</li>
	<li> Correia, RA. 2014. <a target="_blank" href="https://ueaeprints.uea.ac.uk/50549/1/Thesis_complete_v_corr.pdf#page=24">"Effects of Climate and Land Management Changes on Conservation of Mediterranean Cork Oak Woodlands and Their Bird Communities."</a> University of East Anglia, UK.</li>
	<li> Crego, R. D. 2012. <a target="_blank" href="http://search.proquest.com/docview/1313220759">"Modeling the distribution of meadows in arid and Semi-Arid Patagonia, Argentina: assessing current distribution and predicting response to climate change. Carbondale."</a> Department of Forestry, Southern Illinois University</li>
	<li> Cruz, Leyva;, and Amhed Isidro. 2014. <a target="_blank" href="http://www.biblio.colpos.mx:8080/jspui/handle/10521/2247">"Cambio Climático Y Distribución Potencial Del Bosque Mesófilo de Montaña En El Centro de México."</a> Colegio de Postgraduados.</li>
	<li> Egeru, A. 2014. <a target="_blank" href="http://erepository.uonbi.ac.ke/handle/11295/75781">"Assessment of Forage Dynamics under Variable Climate in Karamoja Sub-Region of Uganda."</a> University of Nairobi.</li>
	<li> Fant, C, CA Schlosser, X Gao, K Strzepek, and J Reilly. 2014. <a target="_blank" href="http://dspace.mit.edu/handle/1721.1/92402">"A Framework for Analysis of the Uncertainty of Socioeconomic Growth and Climate Change on the Risk of Water Stress: A Case Study in Asia. MIT Joint Program on the Science and Policy of Global Change."</a> </li>
	<li> Friedman, R. 2014. <a target="_blank" href="http://www.researchgate.net/profile/Rachel_Friedman4/publication/269616565_Cocoa_in_a_Changing_Climate_Projecting_Hot_Spots_of_Vulnerability/links/548ff2280cf225bf66a807a1.pdf">"Cocoa in a Changing Climate: Projecting Hot Spots of Vulnerability."</a> </li>
	<li> Gotor, E, C Fadda, and C Trincia. 2014. <a target="_blank" href="https://cgspace.cgiar.org/bitstream/handle/10568/36173/Matching_Seeds_to_Needs_Ethiopia.pdf">"Matching Seeds to Needs-Female Farmers Adapt to a Changing Climate in Ethiopia."</a> </li>
	<li> Halliday, A, A Nowak, and M Lizarazo. 2014. <a target="_blank" href="https://cgspace.cgiar.org/handle/10568/49664">"Climate-Smart Agriculture in Costa Rica. Washington D.C., USA."</a> </li>
	<li> Halliday, A, C Medellín, A Nowak, and M Lizarazo. 2014. <a target="_blank" href="https://cgspace.cgiar.org/handle/10568/51364">"Climate-Smart Agriculture in Grenada. Washington D.C., USA."</a> </li>
	<li> Halliday, A., Nowak, A. & Lizarazo, M. 2014. <a target="_blank" href="https://cgspace.cgiar.org/bitstream/handle/10568/49665/CSA-in-El-Salvador.pdf">"Climate-Smart Agriculture in El Salvador. Washington D.C., USA."</a> </li>
	<li> Headquarters, B, V dei Tre Denari, and A Walter. 2014. <a target="_blank" href="http://www.bioversityinternational.org/uploads/tx_news/SAPM_2014__2024_1725.pdf">"Strategic Action Plan to Strengthen Conservation and Use of Mesoamerican Plant Genetic Resources in Adapting Agriculture to Climate Change."</a> </li>
	<li> Jalloh, Abdulai, Gerald C. Nelson, Timothy S. Thomas, Robert Zougmoré, and Harold Roy-Macauley, eds. 2013. <a target="_blank" href="http://www.ccafs-climate.org/citations/">"West African Agriculture and Climate Change: A Comprehensive Analysis."</a> IFPRI Research Monograph. Washington: International Food Policy Research Institute. Available at IFPRI.org.</li>
	<li> Jones, H. 2013. <a target="_blank" href="http://dukespace.lib.duke.edu/dspace/handle/10161/6819">"Mechanistic Habitat Modeling with Multi-Model Climate Ensembles."</a> Nicholas School of the Environment and Earth Sciences, Duke University.</li>
	<li> Kate, P.,2012. <a target="_blank" href="http://www.ccafs-climate.org/citations/">"Using a spatial model of geodiversity to guide conservation within mountains at the pan-tropical-scale"</a> PhD. Thesis. University of Southampton</li>
	<li> Läderach, P. 2011. <a target="_blank" href="http://www.eldis.org/go/home&id=60505&type=Document#.UvzKPLTpF8E">"Predicting the Impact of Climate Change on the Cocoa - Growing Regions in Ghana and Cote d’Ivoire."</a> CGIAR Research Program on Climate Change and Food Security (CCAFS).</li>
	<li> Laderach, P. and A. Eitzinger 2011. <a target="_blank" href="http://www.eldis.org/go/home&id=59073&type=Document#.UvzKU7TpF8E">"Future Climate Scenarios for Uganda’s Tea Growing Areas."</a> Cali, Colombia - Managua, Nicaragua, International Center for Tropical Agriculture (CIAT).</li>
	<li> Laderach, P. and A. Eitzinger 2012. <a target="_blank" href="http://www.coffeeandclimate.org/reports_studies.html">"Future Climate Scenarios for Tanzania’s Arabica Coffee Growing Areas."</a> Cali, Colombia, International Center for Tropical Agriculture (CIAT).</li>
	<li> Läderach, P., A. Eitzinger, et al. 2011. <a target="_blank" href="http://dapa.ciat.cgiar.org/wp-content/uploads/2011/07/Methodology-Report.pdf">"Adaptation by agricultural communities to climate change through participatory & supply chain inclusive management."</a> Managua, Nicaragua and Cali, Colombia, International Center for Tropical Agriculture (CIAT).</li>
	<li> Lhendup, P., E. Wikramanayake, et al. 2011. <a target="_blank" href="http://www.wwfbhutan.org/?201392/Climate-Change-Vulnerability-Assessment-of-Wangchuck-Centennial-Park">"Climate Change Vulnerability Assessment Of Wangchuck Centennial Park."</a> Thimphu, Bhutan, World Wildlife Fund.</li>
	<li> Marengo, J. 2012. <a target="_blank" href="http://www.ccafs-climate.org/downloads/docs/marengo_2013_future_cc_projections_latin_america_region.pdf">"Future climate change projections for the Latin American region (from Mexico southwards)."</a> National Institute for Space Research (INPE).</li>
	<li> Monserrate-Rojas, F. 2012. <a target="_blank" href="http://repositorio.usfq.edu.ec/handle/23000/2425">"Modelamiento con el apoyo de Sistemas de Información Geográfico de los efectos de cambio climático sobre parientes silvestres de cultivos prioritarios para la alimentación y la agricultura: Estudio de caso fríjol común."</a> Quito, Ecuador, Universidad San Francisco de Quito.</li>
	<li> Muthoni, F. K. 2010.  <a target="_blank" href="http://www.gem-msc.org/Academic%20Output/Academic%20Output%202008/GEM-Francis%20Kamau%20Muthoni-22134.pdf">"Modelling the spatial distribution of snake species under changing under changing climate scenario in Spain. "</a> MSc. Thesis. University of Twente.</li>
	<li> Nowak, A, M Lizarazo, and P Imbach. 2014. <a target="_blank" href="https://cgspace.cgiar.org/bitstream/handle/10568/51366/CSA-in-Argentina.pdf">"Climate-Smart Agriculture in Argentina. Washington D.C., USA."</a> </li>
	<li> Nyairo, BR. 2014. <a target="_blank" href="http://erepository.uonbi.ac.ke/handle/11295/75029">"Applicability of Climate Analogues for Climate Change Adaptation Planning in Bugabira Commune, Burundi."</a> University of Nairobi.</li>
	<li> Ortega-Fernandez, L. A. 2013. <a target="_blank" href="http://www.ccafs-climate.org/citations/">"Propuesta de sustracción de una porción de la Zona de Reserva Forestal del Pacifico en el muncipio de El Tambo - Cauca."</a> Convenio de asociación 033 de 2012 entre INCODER y Fundación Ecohabitats. Popayan, Cauca. Convenio de asociación 033 de 2012 entre INCODER y Fundación Ecohabitats. Popayán, Cauca, Fundación Ecohabitats.</li>
	<li> Pérez, J. R. R. and J. E. B. Vargas 2013. <a target="_blank" href="http://revistas.udistrital.edu.co/ojs/index.php/revcie/article/view/5073">"Análisis de escenarios de cambio climático A1B, A2 y B1 para la reserva forestal protectora bosque oriental de Bogotá años 2040, 2070 y 2095 utilizando MarksimGCM"</a> 167-185.</li>
	<li> Pinto, A De, A Haruna, B Creamer, and G Hyman. 2014. <a target="_blank" href="http://www.researchgate.net/profile/Akiko_Haruna/publication/269335598_Low_Emission_Development_Strategies_for_Agriculture_and_Other_Land_Uses_The_Case_of_Colombia/links/548734fb0cf268d28f071e7f.pdf">"Low Emission Development Strategies for Agriculture and Other Land Uses: The Case of Colombia. Colombia."</a> </li>
	<li> Platts, P. 2012. <a target="_blank" href="http://etheses.whiterose.ac.uk/2766/">"Spatial modelling, phytogeography and conservation in the Eastern Arc Mountains of Tanzania and Kenya"</a> University of York, UK</li>
	<li> Platts, P. J., M. Poudyal, et al. 2010. <a target="_blank" href="http://www.york.ac.uk/media/environment/documents/kite/INNOVKAR_WP2_UOY_Report2010.pdf">"Modelling Shea under Climate Scenarios."</a> University of York, UK, Report for INNOVKAR Work Package 2.</li>
	<li> Rawlings, M., C. Lacambra, et al. 2012. <a target="_blank" href="http://www.worldbank.org/content/dam/Worldbank/document/LAC/Climate%20Change%20Adaptation%20Planning%20for%20Cusco_FINAL.pdf">"Climate Change Adaptation Planning in Latin American and Caribbean Cities Complete Report."</a> Cusco, Peru, ICF GHK.</li>
	<li> Rosenmund, A. S. 2012. <a target="_blank" href="http://air.unimi.it/bitstream/2434/170257/2/phd_unimi_R08121.pdf">"An integrated modelling framework for climate change impact assessment on rice production and evaluation of adaptation strategies."</a> A case study in Mali, Università degli Studi di Milano.</li>
	<li> Salvacion, A. R. 2013. <a target="_blank" href="http://cpaf.uplb.edu.ph/">"Estimating Spatio-Temporal Impact of Climate Change on Corn in the Philippines."</a> College of Public Affairs and Development, University of the Philippines Los Baños.</li>
	<li> Sepo Hachigonta, Gerald Nelson, Timothy S. Thomas, and Lindiwe Majele Sibanda, ed. 2013. <a target="_blank" href="http://econpapers.repec.org/RePEc:fpr:ifprib:9780896292086">"Southern African Agriculture and Climate Change: A Comprehensive Analysis."</a> IFPRI Research Monograph. International Food Policy Research Institute (IFPRI).</li>
	<li> Soteriades, A. D. 2011. <a target="_blank" href="http://www.sruc.ac.uk/asoteriades">"Assessing potential environmental shifts under climate change and their implications on agriculture."</a> College of Science and Engineering, School of GeoSciences. Edinburgh, University of Edinburgh. MSc Dissertation.</li>
	<li> The World Bank, CATIE, CIAT. 2014. <a target="_blank" href="https://cgspace.cgiar.org/handle/10568/51770">"Agricultura Climáticamente Inteligente En Argentina. Serie de Perfiles Nacionales de Agricultura Climáticamente Inteligente Para América Latina. Washington, D.C."</a> </li>
	<li> The World Bank, CATIE, CIAT. 2014. <a target="_blank" href="https://cgspace.cgiar.org/handle/10568/52994">"Perfiles Nacionales de Agricultura Climáticamente Inteligente Para América Latina. Washington, D.C."</a> </li>
	<li> The World Bank, CATIE, CIAT. 2014. <a target="_blank" href="http://dapa.ciat.cgiar.org/wp-content/uploads/2015/01/CSA-en-Colombia.pdf">"Agricultura Climáticamente Inteligente En Colombia. Washington D.C., USA."</a> </li>
	<li> Thomas, Timothy, Khandaker Mainuddin, Catherine Chiang, Aminur Rahman, Anwarul Haque, Nazria Islam, Saad Quasem, and Yan Sun. 2013. <a target="_blank" href="http://papers.ssrn.com/sol3/papers.cfm?abstract_id=2310087">"Agriculture and Adaptation in Bangladesh: Current and Projected Impacts of Climate Change"</a>  IFPRI Discussion Paper 01281 (July). Washington: IFPRI. Available at IFPRI.org.</li>
	<li> Thomas, Timothy, Tin Ponlok, Ros Bansok, Thanakvaro De Lopez, Cathy Chiang, Nang Phirun, and Chhim Chhun. 2013. <a target="_blank" href="http://www.ifpri.org/sites/default/files/publications/ifpridp01285.pdf">"Cambodian Agriculture: Adaptation to Climate Change Impact"</a> IFPRI Discussion Paper 01285 (August). Washington: IFPRI. Available at IFPRI.org.</li>
	<li> Waithaka, Michael, Gerald C Nelson, Timothy S Thomas, Miriam Kyotalimye, Michael Waithaka, and Gerald C Nelson. 2013. <a target="_blank" href="http://www.ifpri.org/sites/default/files/publications/ib76.pdf">"East African Agriculture and Climate Change: A Comprehensive Analysis"</a> IFPRI Research Monograph. Washington: International Food Policy Research Institute.</li>
	<li> Zavariz-Romero, B, C Cervantes, and A Nowak. 2014. <a target="_blank" href="https://cgspace.cgiar.org/handle/10568/51365">"Climate-Smart Agriculture in Chiapas, Mexico. Washington D.C."</a> </li>
	<li> Zavariz-Romero, B., Cervantes, C. & Nowak, A. 2014. <a target="_blank" href="https://cgspace.cgiar.org/handle/10568/49671">"Climate-Smart Agriculture in Mexico. Washington D.C."</a> </li>
	<li> Zomer, R., Trabucco, A., Metzger, M., Oli, K. 2013. <a target="_blank" href="http://lib.icimod.org/record/28328/files/WP_13-1.pdf">"Environmental Stratification of Kailash Sacred Landscape and Projected Climate Change Impacts on Ecosystems and Productivity. Working Paper.(ICIMOD), Kathmandu, Nepal."</a> International Centre for Integrated Mountain Development</li>
  </ol>

</div>
{include file='footer.tpl'}